# TODO: remove this, as it is no longer really needed.
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: cloudflare-ddns
  name: cloudflare-ddns
  namespace: networking
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: cloudflare-ddns
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: cloudflare-ddns
    spec:
      containers:
        - env:
            - name: API_KEY
              value: ${SECRET_CLOUDFLARE_TOKEN}
            - name: ZONE
              value: ${SECRET_DOMAIN}
            - name: SUBDOMAIN
              value: local
          image: oznu/cloudflare-ddns:latest
          name: ddns
      restartPolicy: Always