apiVersion: v1
kind: List
items:
  - kind: Namespace
    apiVersion: v1
    metadata:
      name: dev
  - kind: PersistentVolumeClaim
    apiVersion: v1
    metadata:
      name: projector-data
      namespace: dev
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 10G
      storageClassName: openebs-zfspv-default-retain
  - kind: Deployment
    apiVersion: apps/v1
    metadata:
      name: intellij
      namespace: dev
    spec:
      selector:
        matchLabels:
          app.kubernetes.io/instance: intellij
          app.kubernetes.io/name: intellij
      template:
        metadata:
          labels:
            app.kubernetes.io/instance: intellij
            app.kubernetes.io/name: intellij
        spec:
          containers:
            - name: intellij
              image: registry.jetbrains.team/p/prj/containers/projector-idea-u
              ports:
                - containerPort: 8887
                  name: main
                  protocol: TCP
              volumeMounts:
                - mountPath: /home/projector-user
                  name: data
                  subPath: intellij
          volumes:
            - name: data
              persistentVolumeClaim:
                claimName: projector-data
  - kind: Service
    apiVersion: v1
    metadata:
      name: intellij
      namespace: dev
    spec:
      ports:
        - port: 80
          name: main
          targetPort: main
      selector:
        app.kubernetes.io/name: intellij