kind: ConfigMap
apiVersion: v1
metadata:
    name: private-config
    namespace: download
data:
    args.txt: ENC[AES256_GCM,data:Phb3LZ2bGOM3RAjZjCOrqoaE3lGGP2yU2/89y2P32pICwQsNmEKNag0tZ4UGdKNR+OPWoPhdSfQa+5hRBTa1G+rJiPga6vIbExi7kirg6A==,iv:4PEWM40bmGzv4ud9n+2UT3nEhYk4XewUzJ1eNbN0Cdw=,tag:7zFWCV/x++bpRZ9uxYqi8Q==,type:str]
    target.txt: ENC[AES256_GCM,data:QT5VMXlx6fBN5LgGARB6rYSbXoLJUaatT14iL1gPvtq85h0+XW4CHJx9jJykKMI50yOQJpzjPhxKeOusJuB/77/lzCI3FQcx/YBjGnUYpBOP1AENZUyuvOMpOc0VTBtjXdz43uezD1OXzbEqgd19KZEE2hlHlUwJupZzKHmeKwPsRh0CCiZeoyg90bvJ//XeXrj2MzMMpmXnVkELWkhO9hlaIP03bNC7Q1Y0I8a+DwI9kb+WkT3oL8JU9mSL3Wmyn83459MQXoNkUJLSfTKwhcyqU6UOc5zWkGWT01JUNq+gkHECJfL3K/+9nYWbBpR4TQ0Hh/s1gk9VUYntl9VpgbpkMd0pJo0MecJMG6Lvb0EL3vDTzsKXnywbziYFC7JDXDiGmsqqekkKvah1aE29OBxU+p6U2bHdmrEmjq+Kw5xoW1TUp3EyFV3z4zTlgr8wBprfg9ccZ03pKg0r+KO9v1w81UEBTaSnT9E+03HLR6VVhl0ugX9tfwKW5/R9sHwqJalIYN02e+oyaZxaOm9aiucuTX6C5UcMpf6hnudnZ2Yf4r9Zf7L0Ftf+5Xyf,iv:xYAA0bMRYd8YoB7lXBopHHmtWo0oRecHZ+OiwPlzyQw=,tag:IfZOez5Y8BJjGrN7hXvwxw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16j27una9wuv7fwaasztl9u8c4u7tduhuz3mrqhl3n6lkz4svzd7svjpkru
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1Y3oyMTRxTFg3Wmk1U0ZW
            eGh6VXJmaWhtSzBOa1pIT1JPN0RLb25DRVFnClhhbDh3RHdSdS9ZbEhQOHdnVVQr
            cUltV3YrM1VzaUVINURoNlUvZmRFNzgKLS0tIEp2WWFhM0RYaG9yWkxOc211RkdN
            OVJaRThFNnQrcmtwQmw5UDJxZnQyNlEKCCSX+lMjJKSMV7LH19w9LTbBH6OWPuAX
            PhDVwW2UbCQ12zHNEWsv+tLr8qJh3XR8cVPHIRMcLhMsWgDe8GuWnQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2021-12-01T08:57:12Z"
    mac: ENC[AES256_GCM,data:B/ZOGni+7kuRsfUWpeL+YFBr+6u9uYVwcsnU/+gqlyJTX9oZax+SYs8u51YCbJ7Y/tdiEotjkbBM9FkYPskmcqhGq/SLn4m3purNshjJpfHxmcwyuVdAWLUfjctEdFwwftG4Og7UU+LqLpvK6oW/YvscPs/kXz/s+9aVYN1Gdu8=,iv:SvLWpYG2ZnC1T4IQwJkk9QtPmbEoOYC6Jik4wCGzdzY=,tag:HRTp422TLSxL408lQ5ptqQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
