kind: ConfigMap
apiVersion: v1
metadata:
    name: private-config
    namespace: download
binaryData:
    thiesbroetje.txt: gASVawIAAAAAAAB9lCiMCWNzcmZ0b2tlbpSMIElqeThodFpwMms0Y1E3cVBJd3VOSEhuUlRCbmxOeUtjlIwKZHNfdXNlcl9pZJSMCjU0NTUzNDU3MTWUjAVpZ19jYpSMATGUjAZpZ19kaWSUjCRBREIzMTBFQy00QzM5LTRGRkQtQTk3Qi1BMkVBRkVGMDQ1MDGUjAVpZ19wcpRoBowFaWdfdneUjAQxOTIwlIwDbWlklIwcWVlqSWpBQUVBQUVzZmdNOEhhak91ZWVGUmhwb5SMA3J1cpSMaiJBU0hcMDU0NTQ1NTM0NTcxNVwwNTQxNjY5NzQ3ODg5OjAxZjcyM2MxZjcxMDMxNjZlZGNlYjZmYTE2NGQyMzYyN2NlNzNjMDA0NDg5ZmVkY2Q0ZDdkNzU2Mzc3MDUwOGFmNDU5OWQxYyKUjAlzX25ldHdvcmuUjACUjAlzZXNzaW9uaWSUjCA1NDU1MzQ1NzE1JTNBV04zSGlXTjdrc1YxMnAlM0EyNJSMBXNoYmlklIxrIjE0MzZcMDU0NTQ1NTM0NTcxNVwwNTQxNjY5NDkwMjAwOjAxZjczZGI4YTY1YWQwM2Q2MzAwN2IxY2UzYjI4OTRiMzQ3ZTliY2RhZTdmNWY1ZjYxZTRmZDcyNmE1OTEzNDNmZTI0YjliMyKUjAVzaGJ0c5SMcSIxNjM3OTU0MjAwXDA1NDU0NTUzNDU3MTVcMDU0MTY2OTQ5MDIwMDowMWY3OGI0OGU3MzVlN2M3N2U3ZDBiYWU4M2FiN2VmNWRkYzJlNzExZTZmOGVkZDRmNmFjMmQ1M2U5MGZmNTMxZjg3OGVjZDUilHUu
data:
    args.txt: ENC[AES256_GCM,data:A82z99fKcpIbJzTdLzRNMf1lzrB487bbDCoRa7WZL4rp8xfKWJPnXQtG9xNiftTutWoH5HnNdAKPs13tGiFj,iv:3XmeE4Sdfsq9WMUn+pZpH94vRe5S30+bvbPUd8EaYAQ=,tag:xqp08w2hs4zh7eFiWOkuAg==,type:str]
    target.txt: ENC[AES256_GCM,data:sG7M0B4IepyEdWQVcE+twbUK1tvq75fFlGTdrTidJW0/KWJ2LzReErW46E3KcpaG0ckEIfz3jfzEIQTxgQyLwoejpt1quNRderhGmT/J8VHHhOgaQaA7Y6QswoWvaXNtOaPfQCxyG+cxYG8fw5oJ0kdXIbQ8E8tvirF4hds+xH6+vV8XyXQBuXN4MNTVlQtn1p5vhJlKMIVJRZCr19xTcWQY3ZMmnzDqQ+4MP/k50EH59CCySxOg8Y+ZHFv8S9Upeszd3oAdt7h84wzvTkQ4uPbrUdba9uk0dbfIyDKHuKeWqMVX9vG01rhHnG6hmEp550zsrG3bTI81lZdJtUSk57SvW4rggACDMfNp1T+XfTtXqLw6PJtlMyp2bTZxfIP23DQJ17LrWBalqo/aRWuUktXJt+hDQNLm+cvOPFo8Ia7zHatbOUhdtGtCs3oDuZFdU17e1smMfqSG+VCFBEnOgkD/2Xt4WpRYmiIe4wtsk0y9kdFyO42npt+BzZo=,iv:Eef2Op1OM7GodAxmIxZSAVwRwjzkxDMvvvbj5qfnWhg=,tag:PY9iceWhFq2NYVE5YigWOQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16j27una9wuv7fwaasztl9u8c4u7tduhuz3mrqhl3n6lkz4svzd7svjpkru
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTR040d3dsN3o5MzB2YVVY
            ZmEwcW5Da2NubVJhQVhHRDJza29BREp1MkRJCjhuVGZMN1djOU9lQWlnV2p0L3JI
            Q2tmSzhCcVozRmlRZWFndzNhTEVWRFEKLS0tIGl0T05CWHFNb0RCaHFRc3B2MVZt
            OE9hZjdWNGU3SFFRMjB1MVZzS1ZJQ0EKs8Z3mxQwRzkvhfuv66MT28yrvlU/HGQ0
            ZETNk6G3mCvMipkki89I3zkvv6BKmzntBEUPcRXLlZCgU1G9Vh6kFg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2021-11-30T20:45:31Z"
    mac: ENC[AES256_GCM,data:MEk64I5TFdtq90JoA9ytPnIwKrsCad65Att9hCBYuS2kEHOXVKZ2cVOya5ym2fZmT+PZU45A2nBNWbvOJuX8qxgZq1q4yCTtW9VOEfVNhb08hFsJo8yBm8ZXHba2CkIUgkzTb2S7SuzNXTD3S0Zu540skrd+asHUwz3GoNonGgo=,iv:DXgdGLyvjihWXMZQfVQ8QUznPqa31HmhOW3iVcJl0ak=,tag:Jz4vtZJ1vSRdegFNhEqLJw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
