kind: ConfigMap
apiVersion: v1
metadata:
    name: private-config
    namespace: download
binaryData:
    thiesbroetje.txt: gASVawIAAAAAAAB9lCiMCWNzcmZ0b2tlbpSMIElqeThodFpwMms0Y1E3cVBJd3VOSEhuUlRCbmxOeUtjlIwKZHNfdXNlcl9pZJSMCjU0NTUzNDU3MTWUjAVpZ19jYpSMATGUjAZpZ19kaWSUjCRBREIzMTBFQy00QzM5LTRGRkQtQTk3Qi1BMkVBRkVGMDQ1MDGUjAVpZ19wcpRoBowFaWdfdneUjAQxOTIwlIwDbWlklIwcWVlqSWpBQUVBQUVzZmdNOEhhak91ZWVGUmhwb5SMA3J1cpSMaiJBU0hcMDU0NTQ1NTM0NTcxNVwwNTQxNjY5NzQ3ODg5OjAxZjcyM2MxZjcxMDMxNjZlZGNlYjZmYTE2NGQyMzYyN2NlNzNjMDA0NDg5ZmVkY2Q0ZDdkNzU2Mzc3MDUwOGFmNDU5OWQxYyKUjAlzX25ldHdvcmuUjACUjAlzZXNzaW9uaWSUjCA1NDU1MzQ1NzE1JTNBV04zSGlXTjdrc1YxMnAlM0EyNJSMBXNoYmlklIxrIjE0MzZcMDU0NTQ1NTM0NTcxNVwwNTQxNjY5NDkwMjAwOjAxZjczZGI4YTY1YWQwM2Q2MzAwN2IxY2UzYjI4OTRiMzQ3ZTliY2RhZTdmNWY1ZjYxZTRmZDcyNmE1OTEzNDNmZTI0YjliMyKUjAVzaGJ0c5SMcSIxNjM3OTU0MjAwXDA1NDU0NTUzNDU3MTVcMDU0MTY2OTQ5MDIwMDowMWY3OGI0OGU3MzVlN2M3N2U3ZDBiYWU4M2FiN2VmNWRkYzJlNzExZTZmOGVkZDRmNmFjMmQ1M2U5MGZmNTMxZjg3OGVjZDUilHUu
data:
    args.txt: ENC[AES256_GCM,data:dWqG9A7PCcxFUTcRSKC+XqY4M65qA+W/6mwbBheQduzLrn48yNpBkyNyTmpe4bgjWqGB2elI0jm5Ll19ojJUZg==,iv:toqs8rpvYhNnUdNNwApCh//hN8Ag0xFMVUXdP4qPMZw=,tag:axI0hMuJF3kDV5Lmg3C1Pw==,type:str]
    target.txt: ENC[AES256_GCM,data:4mE5zFonlViPqhL43MGuFz5OlxV6IICYb8eatAMm4yb5/L3ps7AM3/8rwoRW1AbZ2dX+pMMEELGPWgFcOOzOR4Lmv83nlcFLgX6B9egE+bZ7esQKEgyxyl8Doy85JrCHxOaIhtJWvcN/MILS/lOp8ZsFpqVCN4vvonBDDirXFt0w1GzNLkrtfPWCzSune0dgrXuCndD9xTvf2cHuIJU7oz1/63eHCUKb8YayEpulB2A5zfK8bEPOA12e9GczdZHfozbLW8z9YYv2W+jixm8zj6qsQPvAhRKhatnjp29TbZvnHdEv88+GMDBPU/sjXvwkog5OT9V8GLr6hCx6FlsrSwNyRlBvfqE04tuRy326sRKeXj0HFHYlNvWBqhszifERENZ+j1m8duWBXxesIIwFOVC5Hl0T1VTb7sOwEDY4dkaARahpzmMR6vG6GbAYdU+PpJVQmtR4O3KuXEJ2oMMEcY5s+13xg9lCLlS0h0nHIXmN1GVBE9bDuNEIa6k=,iv:01cstj6xLnvDMEmuCNpSFRbrgqM5YV3oavsD32q+z38=,tag:xD92c+/qBZv2aL5L0c8sBg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16j27una9wuv7fwaasztl9u8c4u7tduhuz3mrqhl3n6lkz4svzd7svjpkru
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYZ1ZaWlB3M2lHYyt1c045
            U0NvZUJvcHdqQ014cTJZOG1yaEYxejBUQ1VNCmswVFdkMFFEdHlTU3FLdmFZTklj
            bnJZa0dkWFJsaHA0QWNXbE16VFhTZ1kKLS0tIFRIMVoybk9qTE1rdXBicFV1SWxm
            Z2hRMUdrZ0VIc1lObTlqdExHekhRU1kKf6j1w0wlhvUaK+a4Kww6TWJcopY99oH+
            SLpGX4vaarIYMc0ki/2o6D+8IU4YPiYzs+bV6gKkIADJcts8UIZu0g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2021-11-30T20:42:13Z"
    mac: ENC[AES256_GCM,data:7Svw+m7hQxBL5Vp7biTL3p/KV44pybjI2F0InYSYCA+Zh909mvQiPKAc+ICb9w7HbYLkvYIzcu6p6hZHqJ7ZioYh+jCV3kH8gnQjGhoDcSoKwl5UQTsR4q89nl2EMslH0BDDTGQODLJj47N03EIRBw1QH5ArrZLTZIO6hieZegc=,iv:69VzpXadFqcmGbEE0Xzfmlpw3oqjz4GY9FbYfgPA17E=,tag:JZ2tNXtmtBZnWcgrp/urmA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
