apiVersion: v1
kind: List
items:
    - kind: Namespace
      apiVersion: v1
      metadata:
        name: download
    - kind: CronJob
      apiVersion: batch/v1
      metadata:
        name: instaloader
        namespace: download
      spec:
        jobTemplate:
            spec:
                template:
                    metadata:
                        labels:
                            app.kubernetes.io/instance: instaloader
                            app.kubernetes.io/name: instaloader
                    spec:
                        containers:
                            - name: instaloader
                              image: ghcr.io/tbrtje/instaloader:main
                              volumeMounts:
                                - mountPath: /data
                                  name: data
                                - mountPath: /config
                                  name: config
                        restartPolicy: OnFailure
                        volumes:
                            - name: data
                              hostPath:
                                path: /mnt/bigboy/home
                            - name: config
                              configMap:
                                name: private-config
        schedule: "*/15 * * * *"
