apiVersion: v1
kind: List
items:
    - kind: Namespace
      apiVersion: v1
      metadata:
        name: download
    - kind: ConfigMap
      apiVersion: v1
      metadata:
        name: private-config
        namespace: download
      data:
        args.txt: ENC[AES256_GCM,data:ADgRIK7oJ8Qg/G22nL9UeUi6QZHQdo5zejIfAer2E8Nh5pGuIPKC8fu9/kKWYvrQwEYOAPP69iLm+ag5/RTslA==,iv:FOW32jFfoofToVPT4EFAShGtlZlVKzGx9K4mXvzE/mY=,tag:eIU2MfbpOJYQ7NKN05YQZQ==,type:str]
        targets.txt: ENC[AES256_GCM,data:Ykk6nnbSzS5dcKB4DwUzJHbUbW5h72IdIUVSJmmaOSmD5T8wFgAwt4qIAnfzPDcLSRnvAGi9Zo2Az/LiupDVy40a9Ni7n0Iw63vczPMBOf1/XZnTUyCITz32/RShFwP/yuADdzwbRBBVIlm/pjm3s28HmBiV0zYyFsZ2Idcu0nfnxvyJDdbsCo1J5176Abddy9h5G5V85PRvNGhRGhTDXQqYMP08MnkeUYoJSBpwyY8fi439z3nVHq8oMg3jmUV8gOjxLYlAiZ1RiEd51M0ktLqXHDV7fNmBJ5GZEJSTNV7SFLxuw6h34Gk6FYlkP83exn6PEStHV+pTNQRiQ126bnQqx0v2i8f8+SwsgULOJ5UNtt1fVNLR3hV8plztwOyxjUMwOmVZ/XsxXJechQSK+laXFH9TuD5ydVL3H9gf1aWMNmunsWb6na8vyZj+qoD3m7P2fwqPCAbXpr4xdLzJvTTZ6G0MmliHbQvkyT3wMQyqqnBKTZmW9nK9/7lE,iv:0Rs+xuWWhaGGNhcCBRrs0Bgk15mLB2q77yJN5/0mp+E=,tag:glFbopLNCe3QKpnZItp08A==,type:str]
    - kind: CronJob
      apiVersion: batch/v1
      metadata:
        name: instaloader
        namespace: download
      spec:
        jobTemplate:
            spec:
                template:
                    metadata:
                        labels:
                            app.kubernetes.io/instance: instaloader
                            app.kubernetes.io/name: instaloader
                    spec:
                        containers:
                            - name: instaloader
                              image: ghcr.io/tbrtje/instaloader:main
                              volumeMounts:
                                - mountPath: /data
                                  name: data
                                - mountPath: /config
                                  name: config
                        restartPolicy: OnFailure
                        volumes:
                            - name: data
                              hostPath:
                                path: /mnt/bigboy/home
                            - name: config
                              configMap:
                                name: private-config
        schedule: 0 */6 * * *
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16j27una9wuv7fwaasztl9u8c4u7tduhuz3mrqhl3n6lkz4svzd7svjpkru
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaV2VSRlI4NEVUZzhxcEJy
            d1lyUUVDQlppWEM5dWEzeWlWRy9TNG5Za0RjCmorcVRtUkpRTmRDcERUV1c1cy84
            Y1BEUFBBRUpSQ0VpN3pMQWRJYUgzMzQKLS0tIGlzYzB4dE1kQk93Wml4cXM3OFlS
            SXdtWmpjK3hnMXpDSmZiOFU4WWxCb2MK3y95Tqt6rlieQxswP+qNX8qW/p/z3zom
            wRqbbDU5eQyyxiDaAN4UY0vabl2FynELRpyfR98FheLEjfd36kImyA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2021-11-30T20:03:26Z"
    mac: ENC[AES256_GCM,data:HJWPVEocHhKKvdNIXKAlBF+eefvJ0buaxAjMPfGkm3yjv5mkUuheiS7TweespIFyZvD1VVX0ZTzl8XZYnJSo28oipr4sDTDLx9D7IkTr/jEq0xzk1x7+FoApDfRgkYGv0RoImHnmwlFtE63/VeV25QsXP1AfYyktlTcQ6zVzovA=,iv:qviE5UdzXJqg8VqgjWScDhuFwp3pvMIGv+t3j8BuFMU=,tag:4b0f+vdPDpRKW6Mza8ATBQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
