apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: firefly
    app.kubernetes.io/name: firefly
  name: firefly
  namespace: finance
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app.kubernetes.io/instance: firefly
      app.kubernetes.io/name: firefly
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: firefly
        app.kubernetes.io/name: firefly
    spec:
      containers:
      # TODO: somehow fix the reverse proxy issue, as graphs are not showing
      - env:
        - name: APP_KEY
          value: ${FIREFLY_APP_KEY}
        - name: DB_HOST
          value: "db-haproxy.db"
        - name: DB_PORT
          value: "3306"
        - name: DB_CONNECTION
          value: "mysql"
        - name: DB_DATABASE
          value: "firefly"
        - name: DB_USERNAME
          value: ${FIREFLY_DB_USER}
        - name: DB_PASSWORD
          value: ${FIREFLY_DB_PASSWORD}
        - name: TRUSTED_PROXIES
          value: "*"
        - name: APP_URL
          value: "https://firefly.${SECRET_URL}"
        image: fireflyiii/core:latest
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 5
          initialDelaySeconds: 2
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 8080
          timeoutSeconds: 2
        name: firefly-firefly
        ports:
        - containerPort: 8080
          name: main
          protocol: TCP
        readinessProbe:
          failureThreshold: 5
          initialDelaySeconds: 2
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 8080
          timeoutSeconds: 2
        startupProbe:
          failureThreshold: 60
          initialDelaySeconds: 3
          periodSeconds: 5
          successThreshold: 1
          tcpSocket:
            port: 8080
          timeoutSeconds: 2
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/www/html/storage/upload
          name: upload
      restartPolicy: Always
      volumes:
      - name: upload
        persistentVolumeClaim:
          claimName: firefly-upload

---
apiVersion: v1
kind: Service
metadata:
  name: firefly
  namespace: finance
spec:
  ports:
    - port: 80
      name: main
      targetPort: main
  selector:
    app.kubernetes.io/name: firefly