apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: firefly-upload
  namespace: finance
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2G
  storageClassName: openebs-zfspv-default-retain