---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://grafana.github.io/helm-charts
      chart: loki-stack
      version: 2.5.1
      sourceRef:
        kind: HelmRepository
        name: loki-charts
        namespace: flux-system
      interval: 5m
  values:
    loki:
      enabled: true

    promtail:
      enabled: false

    grafana:
      enabled: true
