---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nextcloud-config
  namespace: nextcloud
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10G
  storageClassName: openebs-zfspv-default-retain