# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    LATITUDE: ENC[AES256_GCM,data:L5PNoOS7r0VU,iv:54yWBkQMvkp0hvgqxaMdniXy3+iV/oMQQ+YRC5MF4CY=,tag:8prq8StPlC6YNBLwmlA0Bg==,type:str]
    LONGITUDE: ENC[AES256_GCM,data:BE4/ooWOhKo=,iv:/gylDLDMawdXJGMQjq2e4l2/vpJ0zEg0EJEXZcIDDkE=,tag:Kv8xdo8pjpazh2IIuifNlQ==,type:str]
    ELEVATION: ENC[AES256_GCM,data:TIc=,iv:srywhX79AntRByFbdfdGOxut5FZc+FiCMb+x874ecB8=,tag:vDFTufsWMUkVarx/pU/KRg==,type:str]
    TIME_ZONE: ENC[AES256_GCM,data:LZlsYpzmSE9LilX6bA==,iv:r1BqHob3B3Faq9M8Ith1ygN7qb4hE8Ls3KnkPZopbwo=,tag:PQpWIhzayCuvvJQIisvMNQ==,type:str]
    HOMEASSISTANT_URL: ENC[AES256_GCM,data:6jE4jwJLY3y/rpr28jZGN6ku19LwaLixsTY=,iv:tosdAvP94QVJIvFAgal2TdwRY5EXtxCgI0JmrQlGJwA=,tag:oVvEkKGjcCXBLUsgr9JYSg==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:iS2CsQj0iTfDuBgR8HI=,iv:Ga2zso+tkvMi8t9nBR/wjfDCalccNhhnX4T9KC7GZXk=,tag:uOlTtR5x7coZbMba0K/MTA==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:W+r43rVOUtYdO+GRTBAoXcZkAzpx,iv:nsK3Ha7UI/rNMyXk/z2NRztouk22ksGCU7vVbJbLI7o=,tag:ueOqDapiPWji3FOHW28BSQ==,type:str]
    SECRET_CLOUDFLARE_TOKEN: ENC[AES256_GCM,data:Q/Zed3Wm9ig8D1uVIE3xUTrKRC6ufO77ts2NcLB4+JRyd8P+fJKRkA==,iv:wlN4CXsfYmnB3copmck9ktR2yEfmw8BFdqsRvmRnPgw=,tag:oIhl7uLS+2poKVxrd19J/Q==,type:str]
    PERCONA_DB_ROOT: ENC[AES256_GCM,data:KtOyu221mtY=,iv:E2hZ0etRZLuO5w/nCvRreDfILx9jVYZcdTHMn8Ds9p8=,tag:MUEMBFjgcZfDq81cRDbLeA==,type:str]
    PERCONA_DB_XTRABACKUP: ENC[AES256_GCM,data:VfRK4NcBfiY=,iv:bVEXwqruhIN3cybjjjG/1Y1X7ukdMGCM5EcMMAmpP10=,tag:PrqQ99+Mca2G6c8QghrAXg==,type:str]
    PERCONA_DB_MONITOR: ENC[AES256_GCM,data:GKInwZk+6J4=,iv:UiQCSTCd8jNWKP4RBsemFJX+Yjb0ala5VryYVX7vjzM=,tag:P0jzxwGEvdP9EjVeqGEKEg==,type:str]
    PERCONA_DB_CLUSTERCHECK: ENC[AES256_GCM,data:NkfvUxF1w3w=,iv:icdrfQW6nbEHSEI7v2AnWu04ei+ohs87ODL8bxs4mM8=,tag:tz+NGmXtcAo0p62wBv5bGg==,type:str]
    PERCONA_DB_PROXYADMIN: ENC[AES256_GCM,data:463AgZkUKyI=,iv:T47s/IxRByi0NfChYRdg1DG030isIrdnKq0fv3N55tY=,tag:Q2q6bkPY/kapya5YiFVNDg==,type:str]
    PERCONA_DB_PMMSERVER: ENC[AES256_GCM,data:HfW8EMTIfb4=,iv:dp5pIkD5Z762hRHWF0rFEJnFzrrSJqs/9xgATjJct3M=,tag:KxU3PeharsrKPPsekudIBw==,type:str]
    PERCONA_DB_OPERATOR: ENC[AES256_GCM,data:mnHg5CKCJN4=,iv:3bF7iPlFQUd8qOVqHMxMYrgzpguenhpP7Llwt0XLvfs=,tag:cE9l5JCPxXo7uCtVFAShpQ==,type:str]
    PERCONA_DB_REPLICATION: ENC[AES256_GCM,data:QkCdOQ3+61A=,iv:7SoZsW/0drCQH9NhznAPWsvPIMjs+30N5k/ntB1d+J4=,tag:c99xMXU5eGpFos+Ke4tiEA==,type:str]
    TRUENAS_ACCESS_KEY: ENC[AES256_GCM,data:HUr0yNKRSaU=,iv:LRT/1MnPXwk8SVPWUBErepahUV19Lgix+yufMPwb+tI=,tag:Ee10UgCqk7Q7VJMbXuatjg==,type:str]
    TRUENAS_SECRET_KEY: ENC[AES256_GCM,data:chBnBwa/xtM=,iv:X/KJX9l5MJulWo3S71t6AwpZ6d02UAm73UMsEXf1thk=,tag:GpBTvfseEMWLQSw5FQECNg==,type:str]
    FIREFLY_DB_USER: ENC[AES256_GCM,data:LgvL0wvEPw==,iv:vcn+xHArBaQGCiroK8zvsM0QxR1QYCk7dKZDmmTIBFE=,tag:FhgqOwpzNJlYd+g/9/UuMg==,type:str]
    FIREFLY_DB_PASSWORD: ENC[AES256_GCM,data:HZIxGKG/6Xw=,iv:Twqu08QG2Y0h7jC3FITkEq3bIRbrK6JaBjQ5n0VI5aw=,tag:mm7N5mDxBYDJEx80ZMwXcQ==,type:str]
    FIREFLY_APP_KEY: ENC[AES256_GCM,data:wkei2sds3WMrOMV5DIiPpSzM0T72Uw7oImAcI5OuKZE=,iv:D/O0q50ztd0kreXQKAirG0XPowhubNMbYd5o1jA6cuc=,tag:CdwEYWVOTMUgxAC2ieuXGg==,type:str]
    FIREFLY_COMDIRECT_PW: ENC[AES256_GCM,data:AMgwBMeg,iv:PqT+u/zq7NhR5eJI0xxnKOz92tEhN3/VQA/zO/2jl6I=,tag:4pIgp+DNoFGHOCOmXxKc0A==,type:str]
    FIREFLY_COMDIRECT_USER: ENC[AES256_GCM,data:ehBY7m+cCKk=,iv:xcBFOuekG2uFzwpmuJKox+O/Nzj4zTTLZwwe8hhxA4Q=,tag:QvJPIe2pOBAwbF6vyjIQMA==,type:str]
    FIREFLY_LZO_USER: ENC[AES256_GCM,data:C0nUIjJGNSE=,iv:b1DuyMAqj1H9Wi/WBaiAN5EHzZZNvAxuJcDRpEmb3rU=,tag:ii7HMU4QlaWBLvzkrswZHQ==,type:str]
    FIREFLY_LZO_PW: ENC[AES256_GCM,data:rorwjOs=,iv:5KvMGVMSxnFMYaUlU5brZxqjum7FcBGc08+fj+mEnfY=,tag:suS8Sro4n9pWfgt3RgDETQ==,type:str]
    FIREFLY_OLD_TOKEN: ENC[AES256_GCM,data:t5SycDiodpuZ9xBPww0hVY/s7P4Ht94HE2DdMYBD93ZHZCLaH28hzW0/CPdSTp7coJF+1pSjy2IugaMMGAvFCvYCehs7AQNODBxJfvOUhNv+N1ycEH8IYqg5JZPB44cmFncl3Uexri+g0Qq4K7OLr+Z0g8DJe4DJeJEOc8F4ZLGrAhChhLUgFjpx/MRFHQw40/RnTvsO5J2pFeFGObrIOpgoR22vNxi9vHMD/9R1EMU4ZYyU8V/BqoHRh41dBPHHcJ1Wffg3KV2LuuhUmdQ2EEPZGDklz6AT9VIPKHCg5iuGXqsRGbu8WYdEYgbE0d04kpBe+5RDQbuW8N8hHjb5Dvqyd1qZOi5yTAgvCVi/vCH+dkZe7/8SKxTrKRlc09ykxXmI4TZY3KKxIPyeswOvaWsg3VpB0anhbbq1cAuC7IqHmGfowsXVkyDzp7/ohkPTtpKwd4m6oU/fm2GvYRtpTrwI3ZLX56+uK3WV3W55xyuUFqx55YruqQBPw5bnbUk5aUc/I6nrQ4n13GVIwXhhoV8dZN2IAIDEdIQseiw5dcdqyRI6K0cAJMrqt4x3AWdZp0qXeQKodKEyk4n63xasi6TUBb/hVqZxKbqqOPGi2mqJy+qYDzahTHlkIZv8iCAZ5CHlvGnQ5NDp6WIqKzkMYXcXAN2pD7X6U/NiNXpSg2/kcDS523FRp4tYRNgqIrj8SYttWkS0DngMK9plToVgSZWDfNKoBjOpN/2xtiZJ/0YZ0jZv5EnufeV7BUMqbreX6V4nzJtA8rZJ3+erkcIfs5wxJO4yNdHuloHRr0JN02Wyp7u24DXMVROcAF2xc/uplidybKoNSWRLJetFC+HU/1UIKmQVNjXyj6asoLGlmxvnPerk9A3HZm+oo7qzBVSietne7N20rfvLMO0Q34sGWTMHutSaey2kGTdnw/uQxzITzNG39wZKUgbI9H2Rq3hFREA/K9BcHXs27keK0n2zvB0QxEWHz3g1adYPfXO5hnAQk6UMdJKxaJd53YnMCEWQNPlZXMeAHGfKRhYTcjC+v/2hEQ5rcaihv4eMjkQniFV/IiqnNQdVeQzdKxIExw1ZjmTHY8le1vM7jHEuXMNCASMv+o9SVsjEb28n7D5vb6MQwPUg/UBWDMpTxYmisiXa1P06RWpBxRzzoiaMiLBwMeb0W08YmKX5VCzn9oYMEA2JOwEfAt9JBU0WI95vGFxMJyNX7kRDpvRt4gdWARrQ08iCAGFV3Ml50PUZch73/zD5Q27o34SvX52CRLe7EZf3VKsOneDA4QT6JE25l8gfAb45XvRa,iv:ANQmzT9AEGtjW7jWDjTU016a8X0BsRWow01oLm9UtSw=,tag:cd0uhH2em1YJJH5aSRMXLQ==,type:str]
    FIREFLY_TOKEN: ENC[AES256_GCM,data:czd4zNeeQCupLepZ8NBAtFAo3r6blLlQSpkI/TJu6jLTx9/c/ihr8Xi10WtFCJK9qIStMiUqqyxIPVAS5HBMbcKcILiLlY36kBlc/lgSC1XNwfqg1bY6VXXdEenEqNKbZBDz1ZCmoGMNyqZRMUU7pnwR/fbfwDwjvYnQ7TYcnmxMnDv8OQB40keMW072cVpB6/UysJ5+g6KFooeF5WI5MxvTcWgI3XobGAB3NwxK26OuLWVzP/zvTk2Hr6OsUpceBUvRHuvyJjDvR3WqmnYanBULlBNKOw5XZTrbKIxxWslfP8niW074G7m5aUyQItUvZm0lzZ7Z9xhA3SgDcAI55qoZdbfVazUsdrRTYPgbdKDxbPzzK7YMhqlUawBgdtrjrMErjslvl5LhUk2LzgU8wTJkF+yd1j95E/TMST8Mlk28Tnut/dutTO+qtvnLJGxHBwBeG5NAQ/8/BUSevixhzKCcRibcxSmneTGVxJRMHfHFioVOXRyUHXaqD/jhD/ezjXZcnNO4u6JRntaH3pA7lqbmGzI4+kyuawBycFEBlXZr+nLVQP94T1rsQg3qzTwqvagOw2CtRQTiB3meV9Cv5Y2xtdb06uYwLgHwnNXgBnE5ptES7HwPxLHZgwC9a/CFEi0byXWvFoBIt/8jCshItGrIdrXsM2yM5c5iDVUY58+B8mze+VAEFmOU2BYqdkoR5U5cExoDctCY4Mn/gGt79LtcMfjxn5EMd1dsSdgIrEv08cQRhLRvky8h5sCh3D971nAxQFhhMcNK1MNhn2oRGfgMJhuzuplChDNPyvVGBBLC3/DEmeY+pYCgrWQlXM1s3FHyPzWtICBiqXSsFQ/8vk3VKL7aQl/Fo3l3gC8PpTUl6wr5FBUdNZpgcFlsg8dUV05H/LOHHYgqaH+pdSIepmYHF+cUP96fQuIyY3nvC2wgmctUmF94bEGzIs8KhVGux6WpQOgiMvGSYeR9ix3NBZ45/15vJTCp3Wk0fNrUGNjonAcJN6ibXi/JUaSoZ/unxc4VxUj3wkEHclgykeIgF6bR0dKJxcj4mnoV/NZ/5pwDl/SjMgder6nZ2se9P/FJjY4fXUAZnTr3lZC4mBMQB6UT1QAh6LbpypxbguB46DRgLTr9p+SqkZV8S6oCt6W5mBeqgXrFbtGlA/rDBcQmG93m+DZDOHVUqN9bGox2oyaHfcTkPpvn1sn0ULKX1ikFFYIb4Fme/YDkyZXNF/hnC+2SKtq4NX5QLGiFDZ7MzbfM4/CnIvT1iuhML8S13vBXzSnJ06AGpAZYL48dRSkNF8R0Fa0=,iv:PXkA4/+sVRiMVzW9fUNyAafchiS8w5yXpQSQVyiOxAw=,tag:Etax7wjjC2EM1x/RRXXSLQ==,type:str]
    FIREFLY_CLIENT: ENC[AES256_GCM,data:xbI=,iv:jWx5t/PO1nlKydKnqfetXIFc3R3CKFDJ1cCrjs1iMIs=,tag:hLgrYZXsFrXdxQANCjQcUQ==,type:int]
    NEXTCLOUD_ADMIN_PW: ENC[AES256_GCM,data:6DqeuLI/1g==,iv:SoxmWgk6BqhbQa8vY0kmKCunEQ3zoJOJ9p/WrwPNjWI=,tag:cyKnHhvOZF2Cj2rb+uaVbQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-11-22T19:51:47Z"
    mac: ENC[AES256_GCM,data:IHtfQ4CP1T+OLDnwk5g9TVW/WL0smHEuXAYC4Q3bh76qthuNENbW2KN0lOAXhgru9/pOTAHpdLjfQXMPoKFJxFMiCq2FnV30/NH2I3SWlmeWP7IJkkBXEkwpqIvJF4ITDmzSDQn7V2Xc/z0IIVc0Sim4209y1hgi9PiMU43WZbg=,iv:f7GwK8BR/tdqzboucUnLj4s8oeXmNZ8N18XJPIN+xAU=,tag:baUKC/Gizcm/LgGkmQxIDw==,type:str]
    pgp:
        - created_at: "2021-11-22T19:51:46Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA9O9BfJtL7uSARAAg0Wym/FjjRonkoBOolYv5uGDlT0joD0OQz9iPaI9EjlL
            ebm0V22hCIRN8AQt7xsFxDRxvNSZFGBu5FUBMwAIC0Bbpr3N0oJvmVKThZlTXYVV
            Lu+Sl6fYBndEN2or8JdfSL6JeIo6mnCJbT8zSGkWJldeQfrOzZlK3A4X3oozCHaO
            3rUATZ1/032YOopYf7XCrS2f2W3CK8av9+OonwenLRXQaDGNjoOFTuns/tINyKn8
            EMbJSqrQAFKV4SXGx5U5F8m4SvvhcbXpVhbuljuvauAOsDcKvmFfFCRMfAuBESIf
            eeMPCrvWI7Q6BSD2ED3Hj1b1NXKSBN1bNOA2nMUiYoQBF1YFRsSbGJwodAhxv/Z4
            Wd2wgxWhwO9yCVPsEAKol6Ex4eg6YF9qKPck9xDNN7AanYQNtK0p9z9h7spkf40c
            iFXAAzUy7CVoGWDKJ9EWNAvXMdUmCyPHDsvC51+2Y90qxqfYSBS6oz94qOvqBJaZ
            U5gI70xoH+yMNHCe3DWTmYZWifuy7c56j1AabqJpeyZs+1iqhFPOPTZs985uCnf/
            41c32dpHucn0cCzSr+g5U7LawKN97cwecwxi/UH5eEli1Mt8y0CFKaj0DUp3Ts2z
            E9t1jEPk8jKcvKSy/zm4Q0gFuLhTCBm73BafC3y6J0ZgoYvCOpPxsQarxmMFohLU
            aAEJAhCWbiY87ZIeyHVR0xzHVPjUAHXNvm94oFQstSBJgST20IZ5zg7bC3AmlxJb
            x1VQdceBXeDUFVMNS7E84N+OvhRv7L2ph5dxqZoNSZPjN25Uq9k8GaiByFweoKR5
            2GF91dVkb8XE
            =x2uh
            -----END PGP MESSAGE-----
          fp: 18A1069019499FF42DBD8B47C49E75859AF05A43
        - created_at: "2021-11-22T19:51:46Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA5vMwShvdSVNARAAvE7jdh41//Il/cMph/vkKtweEB0FctDY88YBAk1sJeTz
            rLKlhSLXM0r+ZfIh0M7BDqABw4llSGIzlmdML7RZKIoQAxTJzafDjDbHDkqV2/gz
            3Bhlauxp3GckGBpoEI3QaeUiLaeQBdkAMg7SAbMTKg/n6QCsIccOg+hvjVI0P4y2
            MUaH9xvX+sRtR4mJLrrLu9g3cC4TZbUF+eiDbfnni4PFrkDgyizFJbCeESh2ciac
            tQFZenvz7uLjrcFSkikmERfC9jKdidS1mcZLdjtp1qm4Ru+wfq9P2YAVziOAa0cz
            zo9SxAyMOuNJ4g7u2gKtBot9xikj1QM9Z4Aw70flykvGZA0agm103Xxeotd+yFhp
            9906xclUvbMnDpPMVDaza10njA9YQ+ruLR+I9ngQsK1yTMV/WI+5/tl3ST7N3bEQ
            ioXWw81PBIO35GOwwyuPpygYdMu41XvqDBrbGj5g2xbI60m8/UhFpRx3CwNxg7Ju
            LX3BGepgjkrk6M3w7GcDKaeQBI3R541DLAdpw9WG1XoexEHGg7ommS4vK5fGf8n8
            HETgCmhwrwhXZsEhRQpSCDlGLxsKhSbQDvYByKz41RfmR53B4auv4s8Q8aN/kLO0
            IIT7jKvXpFYJiv1to2lr4ZiiI3w6e8iMhgLWHi+/EuXxZLSSxsM40G/MLUqGlefU
            aAEJAhAjLN3t6AjD+gF+nb3eHBJPAIUSXUbJIHhznXhqLJRgmWCRW31jYLOgXkra
            PTa1ZXb+c28HpnPpOo/k+W51zLX9qrtTwDHIE5aL1P1CjkukD3faobSP/ozonuVw
            Ly3PywCQsV0A
            =IJK7
            -----END PGP MESSAGE-----
          fp: CD950B28F793D1003EE3782A9D3D1784F6FC793A
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
