# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    LATITUDE: ENC[AES256_GCM,data:t6DrylG7gpJj,iv:Lcr+wIcbhwZEgQSBDQnHDrcdH5IWIkoUr/wfWSBDsFo=,tag:dcUrKszPwKdW1DVwWhMxCQ==,type:str]
    LONGITUDE: ENC[AES256_GCM,data:tHY2TWK+XyQ=,iv:ga0sz9Tw85Ik1SgUaR2UZcf859i0W+WODfR+7Z9B/70=,tag:bOLDlLJgLnsWj4S87xY+Qw==,type:str]
    ELEVATION: ENC[AES256_GCM,data:qJg=,iv:Fb2dWg5W1g+zhF7eTtxSWW/iDlGzAWjJh3yuOC+6JYc=,tag:kzdlcvDB4WTYXVotOWG99Q==,type:str]
    TIME_ZONE: ENC[AES256_GCM,data:WnM7q6ZK+7C0OaeQNw==,iv:6iI1NechZDR2oeHJF4eh+Gye4RhFXEnHGRlOK7gQ4yw=,tag:0oAyH8Eh4ux+DINMxVtnKw==,type:str]
    HOMEASSISTANT_URL: ENC[AES256_GCM,data:c8boahY4YqhGbaYk7IldkJV+NEFq+/PpX5M=,iv:TwOZvqGeknzJThkp4UN/AfIiU4RCiZp3gUdaK8wkKuE=,tag:ZqWHryo50+Ldht4g1nqRTA==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:BNCsRwRsHbOeUq9XXpg=,iv:ff0rqAZp02PbbsClDL3gHVEJnRTdl4gNRdShR5W1otg=,tag:31tLYCyS461CP3Iad1mQhg==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:v3TLxXP+iOlDSNVu2gm6oKaYL9wg,iv:IFlUNFK/xafuZIzp6jCqf1z75HaxVHEW0tTEmX5oObY=,tag:JOmoS8nPFhqi11EeLrdvgQ==,type:str]
    SECRET_CLOUDFLARE_TOKEN: ENC[AES256_GCM,data:M5UYUGsevhvu2EzHO1cbs//iJc3fRXK/WI5yNX9gt3hY3O1tnObNXw==,iv:v6YY+OjHWLhXzXn1dzIsyR73mtHiRq4qvf+9roSCjEs=,tag:OMCJO/6B4Thv85vLInFKYQ==,type:str]
    PERCONA_DB_ROOT: ENC[AES256_GCM,data:Mum/ZIrsTwY=,iv:bT/E4WYnoEFUCA3LIJVzm/2riJfoyxftUf0SLo2bBos=,tag:pPXzaUMmBmO19Sa46VePmQ==,type:str]
    PERCONA_DB_XTRABACKUP: ENC[AES256_GCM,data:D9jXpAy1tMk=,iv:1K8yjprVIqf5heCOczN1ZnmTJiDLBYNaw0DdSigkUgg=,tag:IjL1QIWu8+a3K0sA+WLcWQ==,type:str]
    PERCONA_DB_MONITOR: ENC[AES256_GCM,data:aGIKEgUQoC8=,iv:Suy0Jj/9CaT1K8rBU0Qew8uHiwSXM4aazG0WPAyJVNk=,tag:UrPuwzGcUlu2D0SHjbzscQ==,type:str]
    PERCONA_DB_CLUSTERCHECK: ENC[AES256_GCM,data:FW7/BCu5N3s=,iv:ihKC7JzfHIPRqhysCQZgeTlUYQEieHD+dpsQPvbTwDI=,tag:C0tXLcKNgmljYa3L1eebPA==,type:str]
    PERCONA_DB_PROXYADMIN: ENC[AES256_GCM,data:lFUbdWAFKn4=,iv:l+x/3x6Ztq2zDOFLDxRFs/q5njYlsv5m2tPGwRK8esE=,tag:cbBEPAA/suHUPrRmQiplmA==,type:str]
    PERCONA_DB_PMMSERVER: ENC[AES256_GCM,data:PTtTlY2zWsA=,iv:mdO8eSD7E+o7mnce5RV4OqMNlh1hxDJy50Q4BOC7E5k=,tag:uc3AE7l5DKQswUtOy2eVIQ==,type:str]
    PERCONA_DB_OPERATOR: ENC[AES256_GCM,data:3wlKIxeBxqk=,iv:Z/9QfIo0N8FLlTF/cvZQnlZAHJ2K7fGkzNwqgCk/aUE=,tag:RnSqrBjMNIXIsg4SkEjJsg==,type:str]
    PERCONA_DB_REPLICATION: ENC[AES256_GCM,data:R8LbfqGAWyo=,iv:RpJ6CBwEqSkJlt/Q4Do8iq8fHuhti68m/dcrZxnyYCo=,tag:raEKid3mKaKZDdnec/wPLw==,type:str]
    TRUENAS_ACCESS_KEY: ENC[AES256_GCM,data:3ymAXVFrz10=,iv:qXynRPJn8whrUJeuSU+evl0jY0aKbRTz4njUYAIWaQc=,tag:MZDK3imU051qxokH6b2MKw==,type:str]
    TRUENAS_SECRET_KEY: ENC[AES256_GCM,data:f9jFskKnHqY=,iv:uZ819fu0sXjI7W+HCucoERvsPHUUyh0gc6y6/h2kg5g=,tag:dt+C48W/jblfGMW0EN2rfg==,type:str]
    FIREFLY_DB_USER: ENC[AES256_GCM,data:OVO/aH0Z+Q==,iv:r4eAkFnbZuhg5cxU2j928gE6SAsuOPN8REwd1Yp1G0U=,tag:iqH1wiFztauouhEa0AJJ/Q==,type:str]
    FIREFLY_DB_PASSWORD: ENC[AES256_GCM,data:rluHeBcpg5A=,iv:MztBUd97xCJcwgSh5QDLOhM5hZBFe247D5keWeRSx+Q=,tag:KFbH9oJNjyLMz67qob8hUw==,type:str]
    FIREFLY_APP_KEY: ENC[AES256_GCM,data:EMFGnKbpZD0DrdYtDCbYWMUneCdh8wDSpdbJXOcFAzU=,iv:ww4A0zF5on2Rwbhd96GuoPrsnvw8sjDTdbvO5634uKw=,tag:8YFj3ZEqWpL7yx1xGLa4iQ==,type:str]
    FIREFLY_COMDIRECT_PW: ENC[AES256_GCM,data:hef5nUO4,iv:W54x+RPEsVXgrlxpv8UGBaFbFjJnjoV5lL6x6KyJoNs=,tag:suY/G1ybEGw+mWFTwhoprQ==,type:str]
    FIREFLY_COMDIRECT_USER: ENC[AES256_GCM,data:1s+ztkSprPY=,iv:Xz+UUVfAAgQIfk+7w6m3SuXs9r26H6CQiVj8b4VniHc=,tag:AXzTZmBsgy90BRKmCQIcGg==,type:str]
    FIREFLY_LZO_USER: ENC[AES256_GCM,data:0GF/Kd2D58g=,iv:EbSPYdMeH+M0KbSd2dFVKHVKb9drEEfdvddwSCJS9bg=,tag:axO2N7rjXLjlNe/l+OLVsw==,type:str]
    FIREFLY_LZO_PW: ENC[AES256_GCM,data:Xfh//vM=,iv:qPtMg9dnfpISYMpHTCRq9E7olk83xUP8ICXyOcjYxxs=,tag:D6wbXpViUzcfiHbUno6TlA==,type:str]
    NEXTCLOUD_ADMIN_PW: ENC[AES256_GCM,data:s6OtdMWAVg==,iv:ALrECWKTuYYzleOcZXr5GNCRA1ci5WeErvP+zVrogJg=,tag:lBrPJgQYn54xS5zNnSn1qg==,type:str]
    HM_PW: ENC[AES256_GCM,data:tNnxb+1Faw==,iv:E8rclhlA91kzbOL/sKPVJ4DYZorBnJIuIx6nACLol64=,tag:SMXQ3b9Kk7FAOwCN0a1nqQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-11-26T16:35:28Z"
    mac: ENC[AES256_GCM,data:oEte5kObum19JKNaY7pSLr0CY1u06Ux0nQIil9Oxw+zF8IEKpA5AvL8TtBuYt6IAb9oXSLl412bzyR0k6ZRUUY5DNNAH9aq00fQIPT4KVZbwsAELwxBmJ51h5yA3Akqa4gE1nYzvNVVUVig7NTDwZqLxCnojUp4g6tCBNW7hrrc=,iv:3BG856aWET2dXhCaA31KXC95A2UUkpU6uTXnVFZB6/U=,tag:SUcUp+WNCz804A9RPiVKUw==,type:str]
    pgp:
        - created_at: "2021-11-26T16:35:28Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA9O9BfJtL7uSARAAkC2jENifYM+ErBCOgkdxO0IjlYYdW7vXuj8j7W0iHI57
            Ewydtx6fn6aSqn4BFjsB5hEWue6lD6l6m5TwLsE47ctHJf2yl8x+jF1o8ueWvxBb
            OkY0ACbYyxi3hwnkYYYInWobajZ84vDMfsfh/wMK6sCZutH2Ma3Q/3Mi00ZG3+sU
            uwAopYTl5rZ3rudaBI/2wXTFASMJWDA7Tq6+1gIDTAMgd40fuGY4m2YD8CoQn6an
            ur/NjT6vKXCvh8iYr3C/QSziNFC8X3Sl55PezCd68nWsKj2HqMW/2bPgSwl87d1u
            /q2zXDk50g36ZTaXWP5soFBGKGBxSvS0RJ4/ReBqG7GjiEHmtaKWY/A6sMpNc+rD
            jk0Vdv7bIyUm10CqBnBW4otAMUtTAxcun3FdzR5aMy9ke/w8jgL8vJS0vx4/IsvE
            ZTAlFxEYgqHuP2XXNMDN2fusX3DDuJHQqKvDog6lbwxv5i39J1mL/625P3KWAgYt
            g88Is0cbXrz4nLfZS3X3HHzjmxUfT6OwEz00tYxCDXcB9l6TSq0nL+MeH6/w+mVd
            DDPdqY/e0xgueKGWPN91kEPRqwjFFK6WT1cPZh3t3l5BfhJCV7FZEuP847rFrc7O
            ULHixfRy3HrdyDu6IqGXMV9Ba6wYvW6LW1jxYJ9zsjqc7BSpyKynMTclDpG2VMnU
            aAEJAhC2WBQc8295p9zrgMj0KVZNfn8GAaNle2GLz+QNG1HET78CFQbkDV/boAAR
            U8jpFvORSkqqOdwaWDYWPlByJDcIcR9aay0hV8hJP3PxfhCFmHoPJ4Zr9fsYXgyG
            SQbi+fIZ0/1L
            =8uRL
            -----END PGP MESSAGE-----
          fp: 18A1069019499FF42DBD8B47C49E75859AF05A43
        - created_at: "2021-11-26T16:35:28Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA5vMwShvdSVNARAAxbN90JCdnNCI8STdgg0T7YJ6HKExDdtRmu7/nBLEFNUU
            Gvel+CrRXvG2l5ylqOnagsDDtINL0QlP+gZKcGaTqcdj+QClMG8IDn1qGsLPODpU
            kgupjSX0nfOdVrlbe3tuDqVVvUhH7InIqRCH4vQiLkVQgU583glX+2M6ISIJOK6C
            46fgAc/e5Y4UeaDYS/SCM2iiLS2/0tGRjViZVnb5OaPRmDsChCJ5AVYp9grEQjDX
            kKzGQMWd+AFOUyCMdHER53+QdX5A8N6vmxoNptJ38dIhm0J3Hh1+5BL/W758zQfG
            Yv5sE3EZ1G0q1o8tjhBvWjOgBi/B2DQfz6RWqd2N+1QopOhZ1lvQimNaovpi2hlb
            8JD/tbWpQnHlogscSXnbRzCczF8rD40mN4+1lB7ahbCojdBcIdjg/BbCdn/xG8Pz
            N8E4HadW+jLiJC1lZKWaqgUbTzfyNcipKzTU/wnltMa8vLpMDcSLrea4zqwOOPhF
            UfZqZr+khh6+HrCIHusMpSpUtoIEmHYs1pNbchyH8sQ1ucMxnzgGUtTL0uW7UasS
            F/IhQMf4RWGfn2sAlfO1djAZqaKlXs05H0Dx5Y2hpUUoo9alsrFGpxoQDf6Zs1qG
            6dJwGXg+zm0zeteSS8CQlfmOX7mcOHvZ4aulzzN9Ps4zrur9KCv6RWbjBwrrkG/U
            aAEJAhA56yT3sQq6Yh7nehmJZXWTfmKn/OYFMr4Ln4nJ7zuHzQDFTvw0QC3/NNjH
            sfAJ/ReEh+VMf5EshfqLSNeiZD/+n77jEu3kzwfciqk9//MCJHeReDU+XIW9jvvj
            85ZCWiBzE2ar
            =JGDN
            -----END PGP MESSAGE-----
          fp: CD950B28F793D1003EE3782A9D3D1784F6FC793A
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
