# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    LATITUDE: ENC[AES256_GCM,data:YahIvte6PFYB,iv:FNc+/j6mgF1ZCHrEeT9Xf6KA9Z1JABlm0vahF2LU4fE=,tag:cNf0Uzmt+ihkJCjOcKW/Hg==,type:str]
    LONGITUDE: ENC[AES256_GCM,data:3+XyXD2mUjo=,iv:eCr20Mkq6KPjrY92l7tNwKJS+o7+dgPIOCkZpejy8Y0=,tag:fR9RPdq/lp3Hm1g1wiNP8w==,type:str]
    ELEVATION: ENC[AES256_GCM,data:eso=,iv:kv9iUKZe3TvPnzCub8ZJh9yLHtcwzyoO7eK2TNcb/BM=,tag:8xuzIjUSTTfG5wtxCbNdeQ==,type:str]
    TIME_ZONE: ENC[AES256_GCM,data:xXtTZy4ERddPHUk+ZA==,iv:0Lw0+NYiuNKKD3VdAwX9ZotgjwjuJOuPX+afsWIdKwk=,tag:CDGV57Rige4iCFfMJ3Jgmw==,type:str]
    HOMEASSISTANT_URL: ENC[AES256_GCM,data:d7RIHFHvp+mclWMipLZBjc97hgzu/now7SE=,iv:w/Sh8eB+hlbp62pccud0H4GGFDzb1ANtG2PBaqFaysQ=,tag:+OK4i81+LDS816Cm+aZ86g==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:ZpGIHZef1G/py+ES8Dw=,iv:2tV2uFayIJGzgSADpMP7h2ra1EevVCoF0ExBd4lMe2c=,tag:RdI/UIUMJIsH2iyZgx2HVg==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:I/IitttE5bU+FHVBXEWPrDPn7mqX,iv:DMjsHu9Bn6S0TT+UDSykgHg0IXR9DfoYO+petS0LRZ8=,tag:u9NXqLjWPisU5PCa4fhnoA==,type:str]
    SECRET_CLOUDFLARE_TOKEN: ENC[AES256_GCM,data:SLKbXngSJoFw7ENEvB6dPxJe06d7NTxmdHPfnAdCZdnVwv6XVEWe5w==,iv:qgPy/ud3aPCMIGLTrJmagDwD+w/HSXXHZnal96TIknA=,tag:hBZ22eQyG9U7AZMXzDHmdQ==,type:str]
    PERCONA_DB_ROOT: ENC[AES256_GCM,data:JjSWTIMW9Ro=,iv:wiZnN7TvvJasGR75jApHWcn8zqEPW/NQVhmH/s1Ev0c=,tag:mFhBXQ38ibFVC2NJ3ZluGw==,type:str]
    PERCONA_DB_XTRABACKUP: ENC[AES256_GCM,data:Mbi4lzFve/g=,iv:sYWswuySAmCiANRBLkNYbkiYcDWEz2Wag1Oka13TcF4=,tag:Yj9VTX9Z9mj3kW53GzmZHA==,type:str]
    PERCONA_DB_MONITOR: ENC[AES256_GCM,data:ypeIO77aReA=,iv:sr7mAWTEA800fk2k+WwPxxGjO2joGJhkLwMuyqyKU68=,tag:c+6bwa25iylfeDZMQ33UdQ==,type:str]
    PERCONA_DB_CLUSTERCHECK: ENC[AES256_GCM,data:uV9ob6BQ224=,iv:zeF2NS/oYewxzgtS79ObLDxxPyybCUnMKTOpv/9+ksI=,tag:GbEsxG8NyMXNjiFxr14w4g==,type:str]
    PERCONA_DB_PROXYADMIN: ENC[AES256_GCM,data:igNvkqH0JEs=,iv:nVOzA0ZthqFhlqmylmnHMwqj4U5EPSSxeaGz6zdgUd0=,tag:jkHlzvBIHVWR+ll5Xa+CqA==,type:str]
    PERCONA_DB_PMMSERVER: ENC[AES256_GCM,data:eeX9hQSV6yU=,iv:YwCwyRUZXrdotVc3WGpCOK2L0UsOuKrmFXLBaOzJsjg=,tag:80TfAOZCjRlSZLZE22LM+Q==,type:str]
    PERCONA_DB_OPERATOR: ENC[AES256_GCM,data:UjjO2+2Dxxw=,iv:o1DQ3GQseakB5smHv0HrLwO7ASrNOanNhEwk8kUyptE=,tag:HGS7zVyvRlZR2ob8bfj5Ew==,type:str]
    PERCONA_DB_REPLICATION: ENC[AES256_GCM,data:nT62qDsFhhg=,iv:BwFn57DBxDEZQMHTNWqGJVtO/EV23zlsb57Ug3V/cvI=,tag:idK6fxxvvauWLViEOE9Hqg==,type:str]
    TRUENAS_ACCESS_KEY: ENC[AES256_GCM,data:TDwfjjtPNAk=,iv:fxS2zekMm3W10DTEaGdN6TAdnhOoHIGohgw8RjvZRfg=,tag:bICWxmpfct6TEdoGcgtDFw==,type:str]
    TRUENAS_SECRET_KEY: ENC[AES256_GCM,data:sdC+ZU3M+0U=,iv:iGPkb/IxUyA0gfsmxTQYhNobWY+HuwYVprg+KKTQ3hE=,tag:kPk0UKnHrCJI7IUrEOW0GA==,type:str]
    FIREFLY_DB_USER: ENC[AES256_GCM,data:CcGnxR6Inw==,iv:buRfmOdk0pa3BQJ+qg0Vs/A8GWi672vCMGV6s/k2dUE=,tag:egmrr3QOqLXvPu4A6umMSA==,type:str]
    FIREFLY_DB_PASSWORD: ENC[AES256_GCM,data:/N34Pe4ZLnU=,iv:3t0PbxRGfEtIhnAPBPpshvzP3PCTXu60uwE98thRn8A=,tag:H2y3qm+OJzFTEAP6uZix7Q==,type:str]
    FIREFLY_APP_KEY: ENC[AES256_GCM,data:vZmzJvcEdhzOC8rkZ/utmS1X04AE4GT4NGiy9yAILh4=,iv:88J3uVcp2ApJgVeFIhSjnIav4MepwIsqsWLrAXap8jc=,tag:QUAT/P/W8PDPC3mrEJwhLw==,type:str]
    FIREFLY_COMDIRECT_PW: ENC[AES256_GCM,data:JvUQLFxx,iv:grv20yKq83gui0OsaUH2O3M2DOwJvHBmnH1RWBBnvuY=,tag:zUGxNf9K53hWLx6vSdnfLw==,type:str]
    FIREFLY_COMDIRECT_USER: ENC[AES256_GCM,data:0+X1Iim/sRk=,iv:/VrCA7GUWuzQMki2qX24ebFC773ALZcFDQEjUP04xSE=,tag:tN7UQLPUday4sp8sA+fMRw==,type:str]
    FIREFLY_LZO_USER: ENC[AES256_GCM,data:AfalesUQzuA=,iv:ggxtrCaEdPh+k1oVzF0dmQfTvvOxzUvSgJ6wxxX5NEA=,tag:yFP3RJN/Y0GXMVMatb/zKA==,type:str]
    FIREFLY_LZO_PW: ENC[AES256_GCM,data:JrKj+Z8=,iv:7iV8nIn0d31opRVrUje/XJj7fCnorwioLQamSAIbwZ0=,tag:qnNLn/0+962UQrv7w6mwNA==,type:str]
    NEXTCLOUD_ADMIN_PW: ENC[AES256_GCM,data:Ou1N+CgWew==,iv:ZuDmnWAImtvyxBqu7SwD4u0BFUjNkjUbOtL+7Pe29vY=,tag:n9zObenQG8UpeWJ/FxjW3A==,type:str]
    HM_PW: ENC[AES256_GCM,data:3EjLXexGhw==,iv:2qIYQM4ydHUXf6oaabW45MKXZaXrGp32McB76mMYI/I=,tag:gyOkBWHig7SxfYlAgg1f6A==,type:str]
    IL_PRIV_USER: ENC[AES256_GCM,data:VCI5eYo+OL+UZAyj,iv:jyuedZzdWNBUOjLcB1tRhkkEgF/rgXVpPQDLschKFFw=,tag:n3NN7ReC0smQxWrf3kmskA==,type:str]
    TRUENAS_API_KEY: ENC[AES256_GCM,data:o2D1Zm2h/EiQ+PxIuAX7EbCLASsBnzOV1TLecx15XrQeIe6D0CGyQGrL+ft4OFZCCtUFOG7EYqvZRr7blH8UYK+b,iv:XpTO9L+BomDeuO/7edCWHzhzMtaox2qu6P+UVYJJwDE=,tag:BpK4YU76Fok1oBlAMNjcpQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16j27una9wuv7fwaasztl9u8c4u7tduhuz3mrqhl3n6lkz4svzd7svjpkru
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrNktIOG12WFdMY3RoSi91
            aE5jYjU2R1dCelZGMWpzZ1E0RnJPb2NBVTBjCjN4WjAwWUUvWXZQZjVFcm5RVFRD
            VzFDdkNHdnRUVmZZSzVZcFkvMEtlb28KLS0tIGhIQ3AyUWR3OXRBa0hUOUJaNklT
            MEZIL0Q2MFlHeWNxUXZtSVB0N0I5RVkKgZBl/DVm/7CDjSORvkaXxg1/97ojBzhQ
            2F3Qg+cOFX9aWR74IDMpFtiRtaGY/JrQ8yHTXG58YSNPfoonx31qQQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-03-30T09:44:23Z"
    mac: ENC[AES256_GCM,data:TvZg2O68wp50BwBqPgzN3aykMTYU4fqacIYzebceMaT0OOw8OBpeTbRUepNN8nE3tY9DonGrDWLupzVApyE7p4FHGoeSS/eLZyM/pq1rV+n5u5w/iwOX1KG0WXQAskXyOthb9nRKgzmTaZvlAS4FXiTI7lz+YJ41B44XeDDb+P0=,iv:F2Mnomnrg/gPFxvO62llWQnRiM2mkQmILn6FOnUjzOA=,tag:970bvsK8lvkKIqB9H37Ftg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
