# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    LATITUDE: ENC[AES256_GCM,data:MbHt2s23iJca,iv:x/R86hrEPGzRclI0Wv4D/u5r66LRNDO9poxhhGqLfAA=,tag:lKDjmJiuZGBWVnm6ahSb3g==,type:str]
    LONGITUDE: ENC[AES256_GCM,data:EHJaJA7NdkA=,iv:r7qMG1uy5Ta3aHJiSFZ6lzDymmi/9To2WJ65/FFDKRE=,tag:EJz3XM7YsGNLYm/qFhcltg==,type:str]
    ELEVATION: ENC[AES256_GCM,data:S5w=,iv:SDYcfULAwbsvFGOWwcsYQJN/7/vRz1wep28P3/z686s=,tag:ufWG5wq4Cby1cLNiPjfsrQ==,type:str]
    TIME_ZONE: ENC[AES256_GCM,data:ZP4/7G0of+ZMXTIVjA==,iv:Qjq1jGNOPL5RuZrypZPTSdHHxgIqNl0EOkaCAwXMotU=,tag:PR3OzGe6sRjH6pw1O8SV1g==,type:str]
    HOMEASSISTANT_URL: ENC[AES256_GCM,data:s+fLqHY3IPHC2uEwwTNH9ULQhagMelkkiok=,iv:AKqYH8UN5L6FQgkEBj70Gw1azqVD0zsjtUrgwZdCC60=,tag:eBcUuPanLmkChv4PYQejsw==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:4XeBiWOMyiWI4SbshQE=,iv:Vba36WegHK7gOl9swNLrVR18Tb6SHZdOCBT8P4zqni0=,tag:jPm/r14oQ58gc5mAqn2CWw==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:vFwYa1yrDt6SK2rV2WN1tsRBp3lQ,iv:2iPlrMQdrg6ApYO85gbAKcvZc+ARIAkloI2/lXnuOpM=,tag:DI8lzGLNklxKi6/KVUZV7g==,type:str]
    SECRET_CLOUDFLARE_TOKEN: ENC[AES256_GCM,data:QFligEO4yhRJCgwbiWq93W+lFJIE0ZS4WBl7S9Xr9phL6PgSahJFjw==,iv:S2jOk6pKqmEs2P0lWTja61no1ECxFnaG9QSvZscWFzw=,tag:1pViMqXHOkbSkbRXLLYpgQ==,type:str]
    PERCONA_DB_ROOT: ENC[AES256_GCM,data:Aqk5vZ9pXe8=,iv:KP97hh6TeIUc3h39eOFhb0a/56UlSCUwYYtm8a8RhN8=,tag:x3g9mmFwy0IGiC/asIfwTQ==,type:str]
    PERCONA_DB_XTRABACKUP: ENC[AES256_GCM,data:tEQ8+FdLWPM=,iv:5CgcHNWA3haXtNjVK81c8fB4uVWtnuVR/Yqhe/ZTjiw=,tag:vE1Ggcfzp2FVLcl7gEE2xA==,type:str]
    PERCONA_DB_MONITOR: ENC[AES256_GCM,data:MgpzTf15uEk=,iv:X/cSsNYq6+CPNTcVRJwxf4JBxc6xh6II0e01y0BFzm0=,tag:7pbH2I/FXFvEtoovfpimbg==,type:str]
    PERCONA_DB_CLUSTERCHECK: ENC[AES256_GCM,data:SUVPqZtkoKM=,iv:BIiyy5ro1fRmzWpzF0g3NMnRb3MDfkZcdt8F1XUu6ag=,tag:GqpDkMQKcxhaJ1E+r8f2dw==,type:str]
    PERCONA_DB_PROXYADMIN: ENC[AES256_GCM,data:vuGAYgFPpJc=,iv:qwdyxT+SrGWzCQsyzlS0HzrU3hs5G8P5KroUvfwM6Ko=,tag:qtZw/fkNSjp+XFPCkbgLlA==,type:str]
    PERCONA_DB_PMMSERVER: ENC[AES256_GCM,data:nx5yIAryM58=,iv:zCX2hGsMUXR/7/JdFdtiy9aYzXsIol8zUhq07cuGpp0=,tag:nWypJt/zI8HNp9Rem2G6cA==,type:str]
    PERCONA_DB_OPERATOR: ENC[AES256_GCM,data:xYAcy2koip0=,iv:0bhTDhj60au6zr6MGzq7CM671Oq6kPOpdBTRrbkClDY=,tag:YmrXhbYT8hv7JqemU2lodw==,type:str]
    PERCONA_DB_REPLICATION: ENC[AES256_GCM,data:IHO+xhuBEfA=,iv:LDKx54fJphP4Ki8McC0AVHqwSf4GLrl14cEl++Yj3js=,tag:WvAOru6ueJk183KYlXGMKw==,type:str]
    TRUENAS_ACCESS_KEY: ENC[AES256_GCM,data:juf+Q6qUn7Q=,iv:qlmjQXkDuB7pIeOdIy1uohd+oDrCLU+aqO4k+3K5Chc=,tag:GiQ5YUo48Rv00VCK0ks6WQ==,type:str]
    TRUENAS_SECRET_KEY: ENC[AES256_GCM,data:AVomUO/9NHI=,iv:FPuB6ixQbP6oN9peA7A8aGqbXQ3GD6raHb9cCyA8Igg=,tag:Yy+Dmadi2ZFiAqF9iKpqyg==,type:str]
    FIREFLY_DB_USER: ENC[AES256_GCM,data:aki+nj8ogw==,iv:K/wIornt6sZOI0Fg+0atIU8mxfuQBMAhgVEA5n29SZw=,tag:ymilQKKUaaNTjhH9eQtRww==,type:str]
    FIREFLY_DB_PASSWORD: ENC[AES256_GCM,data:8URS+DTC5hs=,iv:jFXotcJg3LdJ26lGS++yDK9faGwU7IVJcnHs76ZBZnY=,tag:KeYOPmQiuokIacp5Ffjx/w==,type:str]
    FIREFLY_APP_KEY: ENC[AES256_GCM,data:0TyqKHjESaQraR7o+Ou0DfM77i6vmQ9d9NFWqwmeN4w=,iv:VD4OPv9hj8nLjbEvBK0TOxrXDduAJfJNASTwNFBT7n4=,tag:OSX1PftXeUJGhhrcYEAD1Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-11-07T17:42:06Z"
    mac: ENC[AES256_GCM,data:OuOb+iq9itSDZlGwj+1ZaDeLbljVjpkKOQULDwtiJW9Tv8Lw8QJ0vTcRzqalMCzPAjIcQMRP6/SzYR3TyVHKd4w90pdSvTh+l5LJf6CpkMSen+K3RX64nlJP+OlYFlMWye/DBo3zSSVrFdvqq8MKKbIspVvVwsvyhf5r9G8x0+0=,iv:YlRD5/ILRtAdEAAd1BcDQWWs6BLjPVep4Zu+jtNyo0c=,tag:/uJFj/r2iztqsGoku5AWhQ==,type:str]
    pgp:
        - created_at: "2021-11-07T17:42:05Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA9O9BfJtL7uSAQ//RjCammQOofpVmdiMT9KwuBFCXj1CBjMYtJX7J8Gp7I07
            9m1SqKFhc7VLI073LL4VVyOCOFDBJJjvuePPRAQf4Uw7/LGh5n5ySxIWXOCOvkUa
            wRktrZZb2wAXeNvueuci90iYZUXjImTP2TPiF8eCxe/AT56kgUy+wCjOBNbSH803
            yMsWfT0DNmRYRiW0cKDmP8tFPhPhZ7nSBAzqyqskmZBO/i0U5a7PGRc48hDGvnnR
            04sBg12Hzvfivtz+s2OomKbzDLhWlb6jmYCQOnOcTF1XBVOv03+NQ+xkOv0zwqhX
            Ad5EbVuKpaI7aeEuG+BWshxJizuucIZe7czHGtwdgSNeFUcV/O62MSSzpS1O0IcF
            3HA3rpYvcVtC9oc5BW+l39lebWrkZf5a8K4q/5f341orUSXe+su38IZiCT0Dgd78
            JCmdUoaxUUa7k5v5VwqxabndAKEgAlTark69Sf/UPGLoZmNiYbSbNrSO1o5tS2H4
            C9+xshBVaP/FXqDGVczbyhzN8zmjzd6f2NUG7KKnCaEyo6TkoCQlsIcXLLI256Dn
            OIw0PogggmPvojemOsKAZOlUh7fX5ijOAAxGUL62BqNND+iIxWlV97HhV3c8fDsC
            T5dsPPIsVb19vtH+Y+vhfZOLzSWhiimKBWASnb21wJcgBQywz6NwiydeeLW7/fbU
            ZgEJAhB5Z8bHSPR+6XHRZjsNiRlgbbGV7N8rfgDF7qOYmzUxUI4pgopJXgdLAIDy
            Mqg/uURpe+QLhnXkIymAY2RRX4NR21u9LiVy7Xc2PTQE8YS9Cny/h261REI2OzWt
            XCGwiI0acQ==
            =hW05
            -----END PGP MESSAGE-----
          fp: 18A1069019499FF42DBD8B47C49E75859AF05A43
        - created_at: "2021-11-07T17:42:05Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA5vMwShvdSVNAQ/+PCeqpzMu+ZIIlp2e8Peii0+F9d/2Gd5MGtDQGz4Wh6dw
            DHJR4+OLAHbjKqH6xIS1GkBNEnwabxoWMkr+TuIODgaaWqvZjijEBmDdrptFpXEx
            VKeCtTwfL+Jv+8GxnadkGlWsg0h1Yqs4qcdyCs97zO/aavLM1N5gl49lZ/vtrBSC
            g9ZX2NVe4Yo5Fwzihodob7uZwaNTCrx6g4YWvVZSvOwD9ONNbMA4T4ujMBUmLyWn
            9VJ16yxnWOXnEFaPXt/9eo/FeHOtYVlwTJ8yfvZsSZ4vlynpeD3gyJG/Py5z6AHV
            9kHBYrJBcBx701EPqNnQT7QzlW7qNnEqlQnDDCgzR5rdbkphhCkl6WECM2t2Ezdm
            joj5sRfpz/D85hrcywjoYxaW7vjRUmOQXImLuPh2Dl3eO77WY+hfa0n3D8ECYgsW
            5Q9qIAuLSIHcCS2UNZOFJ4e4jt1WgwaOCBRjzsZm6rsAScOGH40ZaEJQ+BxLO5O6
            Y2bfap9HujppxjDXhxi2XI4mPmZgdPJ8waquoHNpe38dcbqIG7t0khoEcjLdAe6h
            nykl6CdPTEqn2r0CbpKHqzp2dAnRs/VKjdFyxn0mJq4xinY63Aa63cyOnWUhreuo
            PQYif61/Q6PyC+YpI87YxwsN/Zx7tG297/ZBC7FO4FuEptBgNhK1XCCpoIlSPmrU
            ZgEJAhDb06TStyicG9cddCOoVW58iL8R542/gPtrKQi/+5r+Z/FEB3MIB/l1qLE8
            rPDZ79YQlwHydZ1PKCN9PaD03omSCRpBA7HHRMIyCLuDHfPTOMuSVIyg6h9bwM5J
            s0dt97VcKA==
            =s4ej
            -----END PGP MESSAGE-----
          fp: CD950B28F793D1003EE3782A9D3D1784F6FC793A
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
