# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    LATITUDE: ENC[AES256_GCM,data:bnkqxQQFl01t,iv:H5ZfKbwlF/sq/yuPxtXvXMoG6bTkH/nAYW/oKHf+s/U=,tag:KgSX1MFoYhNDeKxRjrrOvg==,type:str]
    LONGITUDE: ENC[AES256_GCM,data:oqvyfvb/nt0=,iv:om8fW43v11luvGwa31qiDWoTEEEXzQ29wQLWfGakRhc=,tag:rhrGwXifTvGSOFDAniZluA==,type:str]
    ELEVATION: ENC[AES256_GCM,data:1Vc=,iv:CAdFJI9O/QrJ2Pv5EmdRploIf4mqAQxItft+AZ4cVCY=,tag:KB5Y3lDCNi5HKDIBZEILiA==,type:str]
    TIME_ZONE: ENC[AES256_GCM,data:03PoBLdBfSd2LWlqIg==,iv:EgDh1rFqVhAEzvG1T/tuPewfzr/8wqDo9M4KPpaK/Y0=,tag:q/FdIO81HUGQHbEH353sCg==,type:str]
    HOMEASSISTANT_URL: ENC[AES256_GCM,data:iyyL3wZlHNSGsM6GQL9DnPrtxRDmBAU+Ilg=,iv:431fD8zkzFFYe1to+rN2whJHhxicSImhRpqDCUNOjaA=,tag:6UcbHSzKpFEt6LL1R5oybg==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:dUvN2/fDS5A2k3fSwVs=,iv:VkDX1NiKiyF2+jYkbgiB5sV9GFSVfoYPVQnecdRSOO8=,tag:ou22cQJg9pIVy9KC7Ls7yA==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:mAjM7sLZz7snNrp65RHdrsjjw68k,iv:EtokLtPfWvDHoko73Fhtq3/+UWb1GORegPDgCr2WWAw=,tag:Tvh7/d+GYQD56FT0to3VrQ==,type:str]
    SECRET_CLOUDFLARE_TOKEN: ENC[AES256_GCM,data:KoFEJUyfxm4e+Zwy0JB2r3c9r5PdV/PUtjyb2kJLfaaH/ddOdkhXMQ==,iv:kaX4WWeacnugsbLIq3BjE2Zlb58kdT7Q267BS9g4fq0=,tag:T4Uqp39ZUMJ5qSr4n7EBnA==,type:str]
    PERCONA_DB_ROOT: ENC[AES256_GCM,data:wllBzTd3q28=,iv:YrCOW2biRhVHA4iNlPyMkU4NSmyNvzwTcTj3hrFpl/s=,tag:pMepf878r0bobHdgKUk6mQ==,type:str]
    PERCONA_DB_XTRABACKUP: ENC[AES256_GCM,data:mhNpmU5qzQo=,iv:VgiqSqk32RsWVfHyr93w+6MoESemwUC71A3KTcmrhus=,tag:Zm+z1Pg8XrCwPkEi5/qnAw==,type:str]
    PERCONA_DB_MONITOR: ENC[AES256_GCM,data:/WgTjFdxqX0=,iv:52EWODeKLOka618nxYkAl2cTpuZ6/c8r6lEICvUvGHU=,tag:gSy8hT9eovMFRqgly4akPw==,type:str]
    PERCONA_DB_CLUSTERCHECK: ENC[AES256_GCM,data:Dnf/EOSZd/I=,iv:do+D8j/mQe/qcw1qEExFZkfP3x7RFgRHn03kG1rxxnc=,tag:do+JghGhqq9QvNIqlMtwVA==,type:str]
    PERCONA_DB_PROXYADMIN: ENC[AES256_GCM,data:zVPiPU6J3e8=,iv:28VVUToZ18ZiAIzbDuHxYDwTAvinNs966JuVts12Ez4=,tag:TY1abvf/Xa3CcxrBRTypgg==,type:str]
    PERCONA_DB_PMMSERVER: ENC[AES256_GCM,data:x2he6Ud1UF4=,iv:vL4+4CFVWhhWgn/YSi95Dkzf9BPgEBaow3d+jcyxE/4=,tag:TlLWFxDjFvPxANy/IAWLWw==,type:str]
    PERCONA_DB_OPERATOR: ENC[AES256_GCM,data:3UZf6fQI6/o=,iv:Q3bct8k2LNnPNWQ9FKb4Nt16PLIwgcnJDlSN+FNxTxY=,tag:fk6aUK6Km7qRY0iW6GpUxw==,type:str]
    PERCONA_DB_REPLICATION: ENC[AES256_GCM,data:kGWoLDex9A8=,iv:fc+NFK/Csef2fG7EJ7wqq4myJqEGw3ImNMrmwegmg+8=,tag:tekoD3aBU6jg3vk9qe7Dag==,type:str]
    TRUENAS_ACCESS_KEY: ENC[AES256_GCM,data:RJIQJtUf+rA=,iv:AXFBdtkP5tgidDWLFX/d1Tn2obzvuTjJcAWFCxjd2C4=,tag:SdHgpx5h6bNiQ1OyYVvrvQ==,type:str]
    TRUENAS_SECRET_KEY: ENC[AES256_GCM,data:zBeUvGJg15Q=,iv:l8CTWGsDCtRY8fZC12s4tt2NYdAaBcp42p8o1dheOFs=,tag:M2Wx+qXHrA+36FU/PzEEJA==,type:str]
    FIREFLY_DB_USER: ENC[AES256_GCM,data:fupDMZ3jdg==,iv:OSHOALrPbhHNnHxjXGCwsTaXAp/BdiUaLYMvMRq3RFQ=,tag:kBjc6bQUmuv9iMlj2Y1BqQ==,type:str]
    FIREFLY_DB_PASSWORD: ENC[AES256_GCM,data:s/PlDHCTtJc=,iv:JZyo5d25MsOnnPWHiRa+Jx+cGn9yzQ3bwo6Jmi2cJDE=,tag:+EaJ7u0bGGqDKb/nerwyOQ==,type:str]
    FIREFLY_APP_KEY: ENC[AES256_GCM,data:q983irsaHl0YnlJoPXZOb1BP2fUMZq9X/y6hB5goS4A=,iv:ZU2Ws/ktf+wv3/rpmRtnX/6HR3mhb18wDXyI2j+bFhY=,tag:Ba7PtMgvB62w3+e3Mx3I5g==,type:str]
    FIREFLY_COMDIRECT_PW: ENC[AES256_GCM,data:uYi8u2xB,iv:pDn0WHRZWVViL0gzW5uLIyG6x0+qVwwcSsuPwmzs4Fk=,tag:7XMwDb4V4DEDIhRdcRkrkg==,type:str]
    FIREFLY_COMDIRECT_USER: ENC[AES256_GCM,data:GfYyQb+94x4=,iv:ENJ27gu1xyRrfk+lTevmAQrf6eT9MEAj6Meu+dAKANI=,tag:MJ5e4Ci0JbAJn2Le8zXnfw==,type:str]
    FIREFLY_LZO_USER: ENC[AES256_GCM,data:b9JG6cK4bfQ=,iv:GAjiPccCogMbPTH2uZUmMeQhgJpZXVaWmyM8OC/InGQ=,tag:sx+K614cdau7Mg2ZJ5kqFA==,type:str]
    FIREFLY_LZO_PW: ENC[AES256_GCM,data:+1ByK98=,iv:dqV983D7Xmz8GV6f9TNP8SuOXTplOBsPBuSGfnqGr+U=,tag:SyQrAwdxGLnS+F66bqzcMQ==,type:str]
    FIREFLY_OLD_TOKEN: ENC[AES256_GCM,data:ZHYP1Xb/wlMUgGenvoY11+kPKzm/AmNCtRXTQAL9bWzag039IYinZCajPUhoExLZjpBkpgc9wVbH2AB/fYGrfkyci0K3xz4E23LVdliSXjLjHCTSpIM1lYHRB2dkdNNNeksUq61PeJaO9W50624gkHpM8426DtYZVKtwBrywELXS6zFKyLeqmLxtwWCb23by18O6vGc01U8W6TwIopO6HngwhHv8Gb0HftCzsLWEz71b77MZD001GyZIEW6l5Xe7FA504sJOJA3suwxxZ8mSC/pgiFK5+IenHREMIzexNaSQObgFqjglQKm2S3OonLPgePAVupJkpYNo1R/mAzwW9bB1BC1BiBMXdGm/uNUEn6NgDxgvfA9GUnE7aFIXpvgFAp6B9T4Wn5i5SHQOjqlQNW+QYVBXd6A2UL0mJyw81QM4T0FbCFgj0JdhX/qW3a+6kwnwcE8V2zZg1Z7omMW59FMhx42j2P44/ebvcXFfAp+Y09AOWLrCXjRS9VzuSiaK+MNDRvz7m3i3a8zs2uL53FF1vPpoeoWFRsT0tvoYtSbtcoTTUFlupkWEOgv62Xw2lY424TYxBLPIMCOIHY1KuZ62/b84l62bLOVcPnYpDLSj54XMgghQMSK3Qn5gXjmvgIrvhGk+gF8+mUTe/G2NTCa09o0MSEW2lwQ505xIsI8eA2h1uvtv9dSxFCb64H8DXNRu81PvrK5vwW67upfXJTCrEwIlHYOQu+Gvtsvx2GojAVThdbRjn5/gOoZAbaQ8twCGLxieiWtdjQzTFgrBqffAd9Bi0hwlHRKIEeRvzBRrUjIlajOhqP5JnM0D00Yq6R97iLasGtqi7wzLCPSFc5pMUt3Y3ppM9zdUX3p14F8Z0pYMuczxH2mHQnZVjMUAXzpzkNqfLackgdelsdnuKvtL3UZme4Ua6uFE584KwHkTpS5fb3XjLcZF2MjvWd1DHqPuMr5vHyX3ywrZnhC8bM/Bs9O5yn6nvNGiohzW7iZe/tOgdhiMGxvaCQtXxhGzDVB4iR3XseC0/PQ+ihRVm9U86NnznshDXvUK7krVu1UCW2htsxUPHNFYVMZAELEnN32F1VxKvbRQlNSWGmLleXbxjzieZL1yEkB15raCvo/MHt7kLi7/8uy1vrbhtOw+lUTi+9qDqGtyG777gBAEAmMURJ4Xshwz/BxInaEBHTAH+Xapo/hqJSCVcjeNg9+WWmsxS29nRM7jo2AzYvJ1NDbrAagTIoq0EWfIDVZY+q84ypcJdH/g4lmgEmzxtKionQPiYGnI4v5DyK1wKcTgYr7/PtAw,iv:+xNi7QjrPL2FMO+54hGSqmy5xyYMguoWjlgpPhX8L1c=,tag:AWJO1tkYkPIRfulsoJkQDw==,type:str]
    FIREFLY_TOKEN: ENC[AES256_GCM,data:68PDQ3RLRc+xUPN5FIM+1h/c5UTPQ7nRF3Uc5KVZC6GZ4FUS6pGc/IynhLwkBrkgf8+rXIvTiKTPFfZYEAZjlOtfBoKipydynoEYSSd0NIdTN55BvO7lvpGCSgskxbpQeUZzvsTPgIS5OZXrDfsIloApnq/NAB1zAkslA5mkvF8gZqa2GZ052aZPsMG0w4nps7sUTc/gxlong2+KoDfWQSldCCtKxTas4hKf7d5jJggxXdY9t2+esjKIFIDhlDEa/GWU0IUXh5xO1cNO/7K8skTn5Bo/mEGf+CYS3jfhPbMNBjruehFKQdnU5LadQKeakRYyMNp7ZyABA1lGbafD3m8nSpYPJSx70ja7oBv6i8wYRxq8KH+xcjL5CrHHGaSQ4mRt5Aggj8VPc4knHvlBAte4IHVh5hz40g/gZfjNr11ueHH94UnANYXM45goBaeJTikPMjEpsFuRJl7Wp9UH6GHYEX5zItj2AHfPM86KM0rIsGdwd5qN4wjZKEOs66HixOhIEbAiDfVbf9k4zluTLeu54M8pDDeecKryXNolnu8aEaKRqmPm8dswheTUqjSyKq2EV4TXunvkDgcBWDhVtrX/G/YrUJhepgf5tQYX6JUFa8Q3aj0Z1KyaFZKLIcjifB0z36PKNuQvNqsLCF5jdnqjUJON+XqvtZLsf5GlmQjSjTpUdZLXEawM9fq7a7/IMCEVnq+Cguem2qZ8PWOp4fWInlIXehsXeBh0Yqr848NnNCceB+F6RvmJ0eP9dFd7USZnhtWvTBZTeEAEPV+9zUm7+GZJcZiaWu4l8OX4MLIPLo6jw/D/Jz7FoUw1bqZjTM3ywHbVFsnh2k2h7ZI+YCyDUNmJSxYXITCEHpLFpIlkBAnI/Wv4odrcFee557wxeIlLPH5YaAV0crz0R2+YyNdAD/1KaD6cPIp0p79syTr6uKxMZA4jD9ts9A1LFjDefUPxS01dvt8RNsRBQS3nDGhAXboAZxSt04G5ZSKvtRR7bCiibtX4QFO8ALclaIo65p1qaU4tyEAka80jnYLEGu8f2ccyuBzdQD+X7/NpbmXme3W5/BGAtub93MVeSdabsnwiJQlWPUQF/AcORQu6k+8kk237dVPX2dv87hboplkjJjThiB2MV0fibOZkUaskuYvx7xGC/Prmjd7Wfkwm2/mMWTn9oeFmlyU4eimuy0BLE0ttH1Qm1TGzuAFx6co3vLY2QiUNVe33xWxJjTrj3wrdRPFC5NY7ItvBn0sQeA6ZPFd9OihARSQfVgNK7uGZR9/cYadYMzgyx5BCr8i5lCboHKs=,iv:ZIuTy5xNpvLBBG8WCFX4ZasEX/lycK/psiHtSPJV8QM=,tag:RTUrMMxDRv/zOhkWvXkYYw==,type:str]
    FIREFLY_CLIENT: ENC[AES256_GCM,data:tSY=,iv:2PSY4UeSgYghfHTi4AiEprv47YrBzjsz3m/DanSiYpM=,tag:1prvQQZ1KrwCAsRi63Rabg==,type:int]
    NEXTCLOUD_ADMIN_PW: ENC[AES256_GCM,data:/8U6m30qXA==,iv:95gfcxTotVCVSj78VHpUmMx6eMc9AGmfjwKMr7zDAYQ=,tag:lFU609EzfenhVyFQ71evfA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-11-22T20:22:40Z"
    mac: ENC[AES256_GCM,data:MAWJ9A5EG8KdSwbDCuS9hoSt7fovokPzP2mxlM09lVuh9n8SL4AnpciqUOw+LbTqZflqx8T7EZFIGkRvGhR+JcBfX9lKvpaE5yk21zG3CQDfHVIGVP/ctbm7zCp4gczF4m9s33xP9tvfvjI1QobRc76uQDf2CRy5uaAFuGS6Hp0=,iv:kiUcCj25Rn2bYJxXuRduc2jhb5cp3bTMPK1eKMWFJKY=,tag:7NTWgIuTzOkk0hgFc6qNig==,type:str]
    pgp:
        - created_at: "2021-11-22T20:22:40Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA9O9BfJtL7uSAQ//U+D+AhrMUOo/NJjwQDLmEPnkHgEQKVobv6XET1PPg7kQ
            nHk/qGg578ehV5CjXjzXcZj5Q0W4Gl8H17JjT5Unl5vernzsFZ5uCZ8oklw+zpAI
            tiCzAx/Y/iGcYMlAMKH7+MKqYIDY9KiKVk6fVmo+QmxwQH5xYKJgNUWggtIl8LCt
            J4mxv3zPgSxITBU70os2zzaqDialv/CARcBX10O/zJzcVaEtTp0j6qZHq45Bxc79
            jXYqOJyo4xQVYW2UJXHIME8ytbf7dOMXoNw+G/M1pKGGM0UpAO2H01kXxZLT3KNl
            L6ZvyY85xgbZ4UMFBxggsrSVY67HyXFa1T6rgyKv1tAGK7a+wmKROqMmtVMfnZIA
            K23z4w8FT3ki66vRjAuxbEg/UF9fIHv6dpLmUb7DL7dUpmH7g9/bpmWZx2+W+LVy
            35ExGqONpPMt1lENHvfxA/am9P5ueopXT455BkytZ5wxMz6NVNJ1qvtJnRPBGwZj
            Z+zwecuhLVerWQkdVN02sgDoYw5gTN8R2EMFk3SbT9QBvRswYo6fyK2w72t5pl6d
            w7qyIyhJhphunhX6uXgeVKlMFS2t9BqecsGlp/vRo0kOdT/cGY38PTpAKHytbKO8
            mU7uf2yokHF+vlljK0ZTTPGeXl2gOxtb6y7QX0NXJeW288seF823adA/Mo3aou/U
            aAEJAhB0U27/fAZeJ9mKSPsFt/oR85K91HDMw3LKqdxn6sBkQSYw5NUj/WlHPGzy
            9aQwWHniN0FawTh8uN+BNJqByXk4csHazBZ+7RxCV8ky94SNaVZ86o9MiHn0t/gR
            mWYUxyVhjfZO
            =dGMl
            -----END PGP MESSAGE-----
          fp: 18A1069019499FF42DBD8B47C49E75859AF05A43
        - created_at: "2021-11-22T20:22:40Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA5vMwShvdSVNAQ//U4AifVrs91VkVbnUIRl1UL7qyac1cylqQajQ9T0TvgNl
            wtxzqeoLpqir6XWJG66DIN0yV51PqWTnnep0gF3EUvBf3xeTGd327L0FlxELRe7f
            Tf3OOow1Fm1rb4TADLiItNFuZAhRBfbs0jZ23ep8gFl+x1QHfD6DpxU1z509X66v
            n4ehDyws/HYVYTFHbC1lqkRneoZxs+6G/RDpq9mUkq19z0o1Tqzp3xSOC9IvU0SU
            1I4IVqGUSTwHhxZ8eNppyVN1qCTnQtKnGGTJhM800MgBV0fsnprU9f+zk2oZZXQx
            p9U9On0x2B0fyfs0kAP01TpIuEOgQ+SLfdRzD3WWh0Qy235ORy1AmGEDjuEfJB5F
            ipDMbotcPTZfBNusUkUKWJY0iOpSaCbs+0obSSBkwYXsRR7wtn4J+ut5FBNcH1/l
            rNbBK+YOJW/g2Zbm65hRPK0qI04gz8mA3wXwW5ZbYRYeirdETRQHvSeg6we3ozIO
            bdH35OnXOYi/w17gkWkKbjcthW/FREGyda+VRHC+sRYK7iuwY2r6UvY4HKc2gKxl
            jCi03MVxgsNDYeHOWSFI0yaKessQRfXaWTbCsaLJf8cCCG8rk7InzIrGjy/JTTQp
            1iOmPBTnRId54KQlHsP+kse7/MFwzgouBB5SsrAp2kleTGlb75RlouGOafIQdGbU
            aAEJAhCijm5O+rG/NclbJ9WDe9hBzgSgybnKaSR3+opgKoNysPn+hJtKXQSG7MCq
            w6uN7DyGxO5ie6EmwuijFEYpb8ijVT+mYYBkyqsT92sqqfY7doyyy/JggR8JUjfx
            IowLiYa+PSsz
            =efs5
            -----END PGP MESSAGE-----
          fp: CD950B28F793D1003EE3782A9D3D1784F6FC793A
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
