apiVersion: apps/v1
kind: Deployment
# TODO: Import existing PVC and Namespace into the repo
metadata:
  labels:
    app.kubernetes.io/instance: plex
    app.kubernetes.io/name: plex
  name: plex-main
  namespace: ix-plex
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app.kubernetes.io/instance: plex
      app.kubernetes.io/name: plex
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: plex
        app.kubernetes.io/name: plex
    spec:
      containers:
      - env:
        - name: PGID
          value: "568"
        - name: GROUP_ID
          value: "568"
        - name: GID
          value: "568"
        - name: TZ
          value: Europe/Berlin
        - name: UMASK
          value: "002"
        image: lscr.io/linuxserver/plex:version-1.25.2.5319-c43dc0277
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 5
          initialDelaySeconds: 2
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 32400
          timeoutSeconds: 2
        name: plex
        ports:
        - containerPort: 32400
          name: main
          protocol: TCP
        readinessProbe:
          failureThreshold: 5
          initialDelaySeconds: 2
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 32400
          timeoutSeconds: 2
        resources:
          limits:
            cpu: "4"
            memory: 8Gi
          requests:
            cpu: 10m
            memory: 50Mi
        securityContext:
          allowPrivilegeEscalation: true
          privileged: true
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        startupProbe:
          failureThreshold: 60
          initialDelaySeconds: 3
          periodSeconds: 5
          successThreshold: 1
          tcpSocket:
            port: 32400
          timeoutSeconds: 2
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /config
          name: config
        - mountPath: /dev/dri
          name: device-0
        - mountPath: /data
          name: list-0
        - mountPath: /transcode
          name: transcode
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      serviceAccountName: default
      terminationGracePeriodSeconds: 10
      volumes:
      - name: transcode
        emptyDir: {}
      - name: config
        persistentVolumeClaim:
          claimName: plex-config
      - hostPath:
          path: /dev/dri
          type: ""
        name: device-0
      - hostPath:
          path: /mnt/bigboy/Media
          type: Directory
        name: list-0
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: overseerr-config
  namespace: ix-plex
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2G
  storageClassName: openebs-zfspv-default-retain
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: overseerr
    app.kubernetes.io/name: overseerr
  name: overseerr-main
  namespace: ix-plex
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app.kubernetes.io/instance: overseerr
      app.kubernetes.io/name: overseerr
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: overseerr
        app.kubernetes.io/name: overseerr
    spec:
      containers:
      - env:
        - name: TZ
          value: Europe/Berlin
        image: lscr.io/linuxserver/overseerr:latest
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 5
          initialDelaySeconds: 2
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 5055
          timeoutSeconds: 2
        name: overseerr
        ports:
        - containerPort: 5055
          name: main
          protocol: TCP
        readinessProbe:
          failureThreshold: 5
          initialDelaySeconds: 2
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 5055
          timeoutSeconds: 2
        startupProbe:
          failureThreshold: 60
          initialDelaySeconds: 3
          periodSeconds: 5
          successThreshold: 1
          tcpSocket:
            port: 5055
          timeoutSeconds: 2
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /config
          name: config
      restartPolicy: Always
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: overseerr-config
---
apiVersion: v1
kind: Service
metadata:
  namespace: ix-plex
  name: overseerr
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: main
      name: main
  selector:
    app.kubernetes.io/name: overseerr
