apiVersion: v1
kind: ConfigMap
metadata:
  name: homeassistant-config
  namespace: iot
data:
  configuration.yaml: |
    homeassistant:
      name: Moorweg
      latitude: ${LATITUDE}
      longitude: ${LONGITUDE}
      elevation: ${ELEVATION}
      time_zone: ${TIME_ZONE}
      unit_system: metric
      currency: EUR
      external_url: https://home.${SECRET_URL}
      internal_url: ${HOMEASSISTANT_URL}
    dhcp:
    api:
    frontend:
    history:
    logbook:
    recorder:
    ssdp:
    zeroconf:
    person:
    my:
    mobile_app:
    config:
    # Text to speech
    tts:
      - platform: google_translate
    http:
      use_x_forwarded_for: true
      trusted_proxies:
          - 10.0.0.0/8
          - 172.16.0.0/16
          - 192.168.178.0/24
    group: !include groups.yaml
    automation: !include automations.yaml
    script: !include scripts.yaml
    scene: !include scenes.yaml