apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: homeassistant
    app.kubernetes.io/name: home-assistant
  name: homeassistant
  namespace: iot
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app.kubernetes.io/instance: homeassistant
      app.kubernetes.io/name: home-assistant
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        k8s.v1.cni.cncf.io/networks: '[
                            { "name": "macvlan-main-net",
                              "ips": [ "192.168.178.99/24" ],
                              "mac": "76:df:5c:a1:3f:5a",
                              "gateway": [ "192.168.178.1" ]
                            },
                            { "name": "macvlan-iot-net",
                              "ips": [ "10.0.1.99/24" ],
                              "mac": "76:df:5c:a1:3f:5b"
                            }]'
        configmap.reloader.stakater.com/reload: "homeassistant-config"
      labels:
        app.kubernetes.io/instance: homeassistant
        app.kubernetes.io/name: home-assistant
    spec:
      containers:
      - env:
        - name: PGID
          value: "568"
        - name: GROUP_ID
          value: "568"
        - name: GID
          value: "568"
        - name: PUID
          value: "568"
        - name: TZ
          value: Europe/Berlin
        - name: UMASK
          value: "002"
        image: homeassistant/home-assistant:2021.12
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 5
          initialDelaySeconds: 2
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 8123
          timeoutSeconds: 2
        name: homeassistant-home-assistant
        ports:
        - containerPort: 8123
          name: main
          protocol: TCP
        readinessProbe:
          failureThreshold: 5
          initialDelaySeconds: 2
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 8123
          timeoutSeconds: 2
        resources:
          limits:
            cpu: "4"
            memory: 8Gi
          requests:
            cpu: 10m
            memory: 50Mi
        securityContext:
          allowPrivilegeEscalation: true
          privileged: true
          capabilities:
            add:
              - NET_ADMIN
              - NET_RAW
              - NET_BIND_SERVICE
              - NET_BROADCAST
              - SYS_ADMIN
              - SYS_MODULE
        startupProbe:
          failureThreshold: 60
          initialDelaySeconds: 3
          periodSeconds: 5
          successThreshold: 1
          tcpSocket:
            port: 8123
          timeoutSeconds: 2
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /config
          name: config
        - mountPath: /config/configuration.yaml
          name: configmap
          subPath: configuration.yaml
      dnsPolicy: ClusterFirst
      dnsConfig:
        nameservers:
          - 192.168.178.1
          - 172.17.0.10
      restartPolicy: Always
      securityContext:
        fsGroup: 568
        fsGroupChangePolicy: OnRootMismatch
        runAsGroup: 0
        runAsUser: 0
        supplementalGroups:
        - 568
      volumes:
      - name: configmap
        configMap:
          name: homeassistant-config
          items:
            - key: configuration.yaml
              path: configuration.yaml
      - name: config
        persistentVolumeClaim:
          claimName: homeassistant-config

---
apiVersion: v1
kind: Service
metadata:
  name: homeassistant
  namespace: iot
spec:
  ports:
    - port: 8123
      name: main
      targetPort: main
  selector:
    app.kubernetes.io/name: home-assistant