apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  namespace: iot
  name: macvlan-main-net
spec:
  config: '{
      "cniVersion": "0.3.1",
      "plugins": [
        {
          "type": "macvlan",
          "capabilities": { "ips": true },
          "master": "br0",
          "mode": "bridge",
          "ipam": {
            "type": "dhcp"
          }
        }, {
          "capabilities": { "mac": true },
          "type": "tuning"
        }
      ]
    }'
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  namespace: iot
  name: macvlan-iot-net
spec:
  config: '{
      "cniVersion": "0.3.1",
      "plugins": [
        {
          "type": "macvlan",
          "capabilities": { "ips": true },
          "master": "vlan20",
          "mode": "bridge",
          "ipam": {
            "type": "dhcp"
          }
        }, {
          "capabilities": { "mac": true },
          "type": "tuning"
        }
      ]
    }'