kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: raspberrymatic-config
  namespace: iot
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10G
  storageClassName: openebs-zfspv-default-retain
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: raspberrymatic
  namespace: iot
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://jens-maus.github.io/RaspberryMatic
      chart: raspberrymatic
      version: 3.61.7
      sourceRef:
        kind: HelmRepository
        name: raspberrymatic
        namespace: flux-system
  values:
    persistence:
      existingClaim: raspberrymatic-config
