---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: percona-operator
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://percona.github.io/percona-helm-charts
      chart: pxc-operator
      version: 1.10.1
      sourceRef:
        kind: HelmRepository
        name: percona-charts
        namespace: flux-system
      interval: 5m
  values:
    replicaCount: 1
    watchAllNamespaces: true
