---
name: Schedule - Renovate Helm Releases

on: # yamllint disable-line rule:truthy
  workflow_dispatch:
  schedule:
    - cron: "0 */12 * * *"

jobs:
  renovate-helm-releases:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 1

      - uses: k8s-at-home/renovate-helm-releases@v1
        with:
          # Path to the folder containing your Flux2 Helm Repositories and Helm Releases
          cluster-path: './cluster'
          # Turn on debug logging
          debug: 'true'
          # Do not alter Helm Release files
          dry-run: 'no'
          # Tolerate yaml files with errors instead of aborting on errors
          tolerate-yaml-errors: 'no'

      - name: Create pull request for renovatebot helm-release annotations
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: renovate-annotations
          delete-branch: true
          title: "chore(deps): update renovate annotations"
          signoff: false
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          commit-message: "chore(deps): update renovate annotations"
          body: |
            Update HelmReleases inorder for Renovate to pick up new versions of Helm charts
          labels: renovate/annotations
