---
# todo: make this thing work, because it just doesnt atm.
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pxc-db
  namespace: db
spec:
  interval: 5m
  chart:
    spec:
      chart: pxc-db
      sourceRef:
        kind: HelmRepository
        name: percona-charts
        namespace: flux-system
      interval: 5m
  values:
    pause: false
    allowUnsafeConfigurations: true

    pxc:
      size: 1
      autoRecovery: true
      forceUnsafeBootstrap: false
      disableTLS: true
      resources:
        requests:
          memory: 1G
          cpu: 600m
      affinity:
        antiAffinityTopologyKey: "kubernetes.io/hostname"
      gracePeriod: 600
      persistence:
        enabled: true
        storageClass: openebs-zfspv-default-retain
        accessMode: ReadWriteOnce
        size: 8Gi

    haproxy:
      enabled: true
      size: 1

    logcollector:
      enabled: true

    backup:
      enabled: false