apiVersion: v1
kind: Secret
metadata:
    name: s3
    namespace: db
stringData:
    credentialsAccessKey: ${TRUENAS_ACCESS_KEY}
    credentialsSecretKey: ${TRUENAS_SECRET_KEY}
---
apiVersion: v1
kind: Secret
metadata:
    name: my-cluster-secrets
    namespace: db
type: Opaque
stringData:
    root: ${PERCONA_DB_ROOT}
    xtrabackup: ${PERCONA_DB_XTRABACKUP}
    monitor: ${PERCONA_DB_MONITOR}
    clustercheck: ${PERCONA_DB_CLUSTERCHECK}
    proxyadmin: ${PERCONA_DB_PROXYADMIN}
    pmmserver: ${PERCONA_DB_PMMSERVER}
    operator: ${PERCONA_DB_OPERATOR}
    replication: ${PERCONA_DB_REPLICATION}
